import socket
import json
import struct
import time
import argparse
import datetime
import threading
from protocol import MAX_PDU_SIZE, encode_pdu, recv_pdu as wire_recv_pdu
from input_validation import choice, csv_ids, nonempty, pairs, prompt_until

HOST = "127.0.0.1"
PORT = 4444

def port_number(value):
    value=int(value)
    if not 1 <= value <= 65535: raise argparse.ArgumentTypeError("port must be 1-65535")
    return value

# --- verbose mode setup ---
parser = argparse.ArgumentParser(description="MTGNP Game Client")
parser.add_argument("-v", "--verbose", action="store_true",
                     help="Print every PDU sent/received to the console")
parser.add_argument("--host", default=HOST, help="Server address (default: 127.0.0.1)")
parser.add_argument("--port", type=port_number, default=PORT)
args = parser.parse_args()
VERBOSE = args.verbose
HOST, PORT = args.host, args.port
send_lock = threading.Lock()
stop_event = threading.Event()
last_pong = time.monotonic()

def log_pdu(direction: str, pdu: dict):
    """direction: 'SEND' (C->S) or 'RECV' (S->C)."""
    if not VERBOSE:
        return
    timestamp = datetime.datetime.now().strftime("%H:%M:%S.%f")[:-3]
    label = "C->S" if direction == "SEND" else "S->C"
    print(f"[VERBOSE {timestamp}] [{label}] {json.dumps(pdu)}")

# load card catalog — instance-level (e.g. "mountain_001"), matching what
# the server validates against. Generated by build_catalog.py.
with open("card_instances.json", "r") as f:
    cards = json.load(f)

# temporary deck for player: first 50 distinct card INSTANCES from the catalog
deck_list = list(cards.keys())[:50]

def send_pdu(sock, pdu: dict):
    log_pdu("SEND", pdu)
    with send_lock:
        sock.sendall(encode_pdu(pdu))

def recv_exact(sock, n):
    data = b""
    while len(data) < n:
        chunk = sock.recv(n - len(data))
        if not chunk:
            return None
        data += chunk
    return data

def recv_pdu(sock):
    pdu = wire_recv_pdu(sock)
    if pdu is None: return None
    log_pdu("RECV", pdu)
    return pdu

client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client_socket.connect((HOST, PORT))
print(f"[C] Connected to server at {HOST}:{PORT}")

player_id = prompt_until("Enter a unique player ID: ", lambda x: nonempty(x,"player ID",64))
player_ready = {
    "type": "PLAYER_READY",
    "seq_num": 1,
    "player_id": player_id,
    "deck_list": deck_list
}

# send PLAYER_READY
send_pdu(client_socket, player_ready)
print("[C] Ready state sent. Waiting for server state update...\n")

def heartbeat():
    """Keep-alive runs independently so interactive prompts cannot suppress PINGs."""
    seq = 1
    global last_pong
    while not stop_event.wait(30):
        seq += 1
        sent_at = time.monotonic()
        send_pdu(client_socket, {"type": "PING", "seq_num": seq, "timestamp": int(time.time() * 1000)})
        deadline = sent_at + 10
        while last_pong < sent_at and time.monotonic() < deadline and not stop_event.wait(.2): pass
        if last_pong < sent_at:
            print("[C] PONG timeout; closing connection.")
            try: client_socket.shutdown(socket.SHUT_RDWR)
            except OSError: pass
            return

threading.Thread(target=heartbeat, daemon=True).start()

mulligan_count = 0  # tracks how many times we've mulliganed, used to size cards_to_bottom
latest_state = {}

# main event loop
while True:
    reply = recv_pdu(client_socket)

    if reply is None:
        print("[C] Server disconnected.")
        break

    msg_type = reply.get("type")

    if msg_type == "GAME_STATE_UPDATE":
        state = reply.get("state", {})
        latest_state = state
        phase = state.get("phase")

        print(f"\n=== {state.get('phase')} ===")

        if state.get("phase") == "LOBBY":
            print(f"Players Ready: {state['players_ready']}")
            print(f"Waiting For: {state['waiting_for']}")

        elif state.get("phase") == "MULLIGAN":
            print(f"Turn: {state['turn']}")
            print(f"Active Player: {state['active_player']}")
            print(f"Life Totals: {state['life_totals']}")
            print(f"My Hand: {state['hand']}")
            print(f"Hand Counts: {state['hand_counts']}")
            print(f"Library Counts: {state['library_counts']}")
            print(f"Battlefield: {state['battlefield']}")
            print(f"Graveyard: {state['graveyard']}")
            print(f"Stack: {state['stack']}")

            # Prompt for this player's mulligan decision and send MULLIGAN_CHOICE.
            # seq_num echoes this GAME_STATE_UPDATE's seq_num, per RFC 5.4.
            decision = prompt_until("Keep this hand? (y = keep / n = mulligan): ",
                                    lambda x: choice(x,("y","n"),"mulligan choice"))

            if decision == "y":
                cards_to_bottom = []
                if mulligan_count > 0:
                    print(f"You mulliganed {mulligan_count} time(s); "
                          f"choose {mulligan_count} card(s) to bottom from your hand.")
                    available=list(state["hand"])
                    for i in range(mulligan_count):
                        card = prompt_until(f"  Card {i+1} to bottom: ",
                            lambda x, available=available: nonempty(x,"card ID") if x.strip() in available else (_ for _ in ()).throw(ValueError("card must be a remaining card in your hand")))
                        cards_to_bottom.append(card)
                        available.remove(card)

                send_pdu(client_socket, {
                    "type": "MULLIGAN_CHOICE",
                    "seq_num": reply["seq_num"],
                    "keep": True,
                    "cards_to_bottom": cards_to_bottom
                })
            else:
                mulligan_count += 1
                send_pdu(client_socket, {
                    "type": "MULLIGAN_CHOICE",
                    "seq_num": reply["seq_num"],
                    "keep": False,
                    "cards_to_bottom": []
                })

        elif state.get("phase") == "IN_GAME":
            step = state.get("step")
            hand = state.get("hand", [])
            print(f"Turn: {state.get('turn')} | Active Player: {state.get('active_player')} | Step: {step}")
            print(f"Life: {state.get('life_totals')} | Hand: {hand}")

            # Hand Size Enforcement during Cleanup Step (RFC 7.8)
            if step == "CLEANUP" and state.get("active_player") == player_id and len(hand) > 7:
                excess = len(hand) - 7
                print(f"\n[CLEANUP] Your hand size exceeds 7! You must discard {excess} card(s).")
                discard_list = []
                available=list(hand)
                for i in range(excess):
                    card = prompt_until(f"  Card {i+1} ID to discard: ",
                        lambda x, available=available: nonempty(x,"card ID") if x.strip() in available else (_ for _ in ()).throw(ValueError("card must be a remaining card in your hand")))
                    discard_list.append(card)
                    available.remove(card)

                send_pdu(client_socket, {
                    "type": "DISCARD",
                    "seq_num": reply["seq_num"],  # Echo last GAME_STATE_UPDATE seq_num
                    "card_ids": discard_list
                })

    elif msg_type == "PRIORITY_GRANT":
        # NEW: Basic Priority Passing (RFC Section 8)
        print(f"\n[PRIORITY] You have priority (seq_num: {reply.get('seq_num')}).")
        step = reply.get("step")
        action = prompt_until("Action? p=pass, l=land, s=spell, x=ability, c=concede: ",
                              lambda x: choice(x,("p","l","s","x","c"),"action"))
        
        if action == "c":
            send_pdu(client_socket, {
                "type": "CONCEDE",
                "seq_num": reply.get("seq_num")
            })
        elif action == "l":
            hand=latest_state.get("hand",[])
            land_id=prompt_until("Land card ID: ",lambda x: nonempty(x,"land ID") if x.strip() in hand and cards.get(x.strip(),{}).get("card_type")=="Land" else (_ for _ in ()).throw(ValueError("choose a Land from your displayed hand")))
            send_pdu(client_socket, {"type": "PLAY_LAND", "seq_num": reply["seq_num"],
                                     "card_id": land_id})
        elif action == "s":
            hand=latest_state.get("hand",[])
            card_id = prompt_until("Spell card ID: ",lambda x: nonempty(x,"spell ID") if x.strip() in hand and cards.get(x.strip(),{}).get("card_type")!="Land" else (_ for _ in ()).throw(ValueError("choose a nonland card from your displayed hand")))
            targets = prompt_until("Target IDs (comma-separated, blank for none): ",lambda x:csv_ids(x,"target IDs"))
            cost=cards[card_id].get("cost",{}); payment={k:int(cost.get(k) or 0) for k in "WUBRG"}
            payment["X"]=int(cost.get("Generic") or 0)
            send_pdu(client_socket, {"type": "CAST_SPELL", "seq_num": reply["seq_num"], "card_id": card_id,
                                     "targets": targets, "mana_payment":payment})
        elif action == "x":
            own=[x.get("id") for x in latest_state.get("battlefield",{}).get(player_id,[])]
            source = prompt_until("Permanent/source ID: ",lambda x:nonempty(x,"source ID") if x.strip() in own else (_ for _ in ()).throw(ValueError("choose a permanent you control")))
            targets = prompt_until("Target IDs (comma-separated, blank for none): ",lambda x:csv_ids(x,"target IDs"))
            send_pdu(client_socket, {"type":"ACTIVATE_ABILITY", "seq_num":reply["seq_num"],
                                     "source_id":source, "ability_index":0, "targets":targets,
                                     "cost_payment":{"tap":True,"mana":{}}})
        else:
            send_pdu(client_socket, {
                "type": "PRIORITY_PASS",
                "seq_num": reply.get("seq_num")
            })

    elif msg_type == "PHASE_TRANSITION":
        print(f"\n=== PHASE_TRANSITION: {reply.get('from_phase')} -> {reply.get('to_phase')} "
              f"(turn {reply.get('turn')}, active: {reply.get('active_player')}) ===")
        to_step = reply.get("to_phase"); is_active = reply.get("active_player") == player_id
        if to_step == "DECLARE_ATTACKERS" and is_active:
            opponents=[x for x in latest_state.get("life_totals",{}) if x!=player_id]
            opponent = prompt_until("Defending player ID: ",lambda x:nonempty(x,"player ID") if x.strip() in opponents else (_ for _ in ()).throw(ValueError("choose the opposing player ID")))
            own={x.get("id"):x for x in latest_state.get("battlefield",{}).get(player_id,[])}
            ids = prompt_until("Attacker IDs (comma-separated, blank for none): ",lambda x:csv_ids(x,"attacker IDs"))
            while any(cid not in own or cards.get(cid,{}).get("card_type")!="Creature" or own[cid].get("tapped") for cid in ids):
                print("Invalid input: choose unique, untapped creatures you control.")
                ids=prompt_until("Attacker IDs: ",lambda x:csv_ids(x,"attacker IDs"))
            send_pdu(client_socket,{"type":"DECLARE_ATTACKERS","seq_num":reply["seq_num"],
                                    "attackers":[{"creature_id":x,"target":opponent} for x in ids]})
        elif to_step == "DECLARE_BLOCKERS" and not is_active:
            own={x.get("id"):x for x in latest_state.get("battlefield",{}).get(player_id,[])}
            parsed=prompt_until("Blocks as blocker:attacker pairs (comma-separated, blank for none): ",lambda x:pairs(x,"block"))
            while any(blocker not in own or cards.get(blocker,{}).get("card_type")!="Creature" or own[blocker].get("tapped") for blocker,_ in parsed):
                print("Invalid input: each blocker must be an untapped creature you control.")
                parsed=prompt_until("Blocks: ",lambda x:pairs(x,"block"))
            send_pdu(client_socket,{"type":"DECLARE_BLOCKERS","seq_num":reply["seq_num"],
                                    "blockers":[{"creature_id":b,"blocking_id":a} for b,a in parsed]})
        elif to_step == "ASSIGN_DAMAGE_ORDER" and is_active:
            attacker=prompt_until("Multiply-blocked attacker ID: ",lambda x:nonempty(x,"attacker ID"))
            order=prompt_until("Blocker order (comma-separated): ",lambda x:csv_ids(x,"blocker order",False))
            send_pdu(client_socket,{"type":"ASSIGN_DAMAGE_ORDER","seq_num":reply["seq_num"],
                                    "attacker_id":attacker,"blocker_order":order})

    elif msg_type == "GAME_OVER":
        # NEW: Game Over Notification (RFC Section 6.6)
        print(f"\n==========================================")
        print(f" GAME OVER!")
        print(f" Winner: {reply.get('winner_id')}")
        print(f" Reason: {reply.get('reason')}")
        print(f"==========================================\n")
        
        # Reset local state for the next match
        mulligan_count = 0

    elif msg_type == "PONG":
        last_pong = time.monotonic()
        print("[C] Received PONG")

    elif msg_type == "TRIGGER_ORDER":
        offered = reply.get("trigger_ids", [])
        print("Simultaneous triggers:", offered)
        order = prompt_until("Trigger IDs in desired order (comma-separated): ",
            lambda x: csv_ids(x,"trigger IDs",False) if set(csv_ids(x,"trigger IDs",False))==set(offered) and len(csv_ids(x,"trigger IDs",False))==len(offered) else (_ for _ in ()).throw(ValueError("order must contain every offered trigger exactly once")))
        send_pdu(client_socket, {"type":"TRIGGER_ORDER_RESPONSE", "seq_num":reply["seq_num"], "ordered_trigger_ids":order})

    elif msg_type == "TRIGGER_CHOICE":
        accept = prompt_until("Use trigger? (y/n): ",lambda x:choice(x,("y","n"),"trigger choice"))=="y"
        legal=reply.get("legal_targets",[]); required=reply.get("requires_target",False)
        target = None
        if accept and required:
            target=prompt_until("Chosen target: ",lambda x:nonempty(x,"target") if x.strip() in legal else (_ for _ in ()).throw(ValueError("choose one of the listed legal targets")))
        send_pdu(client_socket, {"type":"TRIGGER_CHOICE_RESPONSE", "seq_num":reply["seq_num"],
                                 "trigger_id":reply.get("trigger_id"), "accept":accept, "chosen_target":target})

    elif msg_type == "ERROR":
        print(f"[ERROR] {reply['code']}: {reply['message']}")

    else:
        print(f"[C] Received: {reply}")

stop_event.set()
client_socket.close()
print("[C] Socket closed")
