import socket
import json
import struct
import time
import argparse
import datetime
import threading
import queue
import os
from protocol import MAX_PDU_SIZE, encode_pdu, recv_pdu as wire_recv_pdu
from input_validation import choice, csv_ids, nonempty, pairs, prompt_until
from deck_builder import build_random_deck

HOST = "127.0.0.1"
PORT = 4444
 
def port_number(value):
    value=int(value)
    if not 1 <= value <= 65535: raise argparse.ArgumentTypeError("port must be 1-65535")
    return value

# --- verbose mode setup ---
parser = argparse.ArgumentParser(description="MTGNP Game Client")
parser.add_argument("-v", "--verbose", action="store_true",
                     help="Print every PDU sent/received to the console")
parser.add_argument("--host", default=HOST, help="Server address (default: 127.0.0.1)")
parser.add_argument("--port", type=port_number, default=PORT)
args = parser.parse_args()
VERBOSE = args.verbose
HOST, PORT = args.host, args.port
send_lock = threading.Lock()
verbose_log_lock = threading.Lock()
stop_event = threading.Event()
incoming_pdus = queue.Queue()
pong_lock = threading.Lock()
pending_pongs = {}
# Defaults follow the RFC recommendations. Environment overrides are useful
# for automated tests without waiting 40 seconds.
PING_INTERVAL_SECONDS = float(os.environ.get("MTGNP_PING_INTERVAL_SECONDS", "30"))
PONG_TIMEOUT_SECONDS = float(os.environ.get("MTGNP_PONG_TIMEOUT_SECONDS", "10"))

def log_pdu(direction: str, pdu: dict):
    """direction: 'SEND' (C->S) or 'RECV' (S->C)."""
    if not VERBOSE:
        return
    timestamp = datetime.datetime.now().strftime("%H:%M:%S.%f")[:-3]
    label = "CLIENT SEND -> SERVER" if direction == "SEND" else "CLIENT RECV <- SERVER"
    rendered = json.dumps(pdu, ensure_ascii=False, indent=2)
    with verbose_log_lock:
        print(f"\n[VERBOSE {timestamp}] [{label}]\n{rendered}", flush=True)

# load card catalog — instance-level (e.g. "mountain_001"), matching what
# the server validates against. Generated by build_catalog.py.
with open("card_instances.json", "r") as f:
    cards = json.load(f)

LAND_MANA_MAP = {
    "Plains": "{W}",
    "Island": "{U}",
    "Swamp": "{B}",
    "Mountain": "{R}",
    "Forest": "{G}"
}

def format_land_display(card_id, card_data, perm_state):
    card_name = card_data.get("card_name", "")
    tapped_status = "TAPPED" if perm_state.get("tapped") else "UNTAPPED"
    mana_color = LAND_MANA_MAP.get(card_name, "{C}")
    return f"[{mana_color}] {card_id} ({card_name}) - {tapped_status}"

SUPPORTED_ABILITIES = {
    "Llanowar Elves", "Elvish Mystic", "Sol Ring", "Merfolk Looter",
    "Prodigal Sorcerer", "Royal Assassin", "Millstone", "Rod of Ruin",
}

# Build a new legal 50-card deck for every client run. Every catalog instance
# has an equal chance of selection, with no fixed land/nonland composition.
deck_list = build_random_deck(cards)

def show_cards(title, card_ids):
    """Print card names and exact protocol IDs for convenient copy/typing."""
    print(f"\n{title} ({len(card_ids)}):")
    if not card_ids:
        print("  (none)")
        return
    for card_id in card_ids:
        info = cards.get(card_id, {})
        cost = info.get("cost", {})
        generic = int(cost.get("Generic") or 0)
        mana_cost = (f"{{{generic}}}" if generic else "") + "".join(
            f"{{{color}}}" * int(cost.get(color) or 0) for color in "WUBRG")
        cost_text = f" cost={mana_cost or '{0}'}" if info.get("card_type") != "Land" else ""
        print(f"  {card_id} — {info.get('card_name', 'Unknown')} "
              f"[{info.get('card_type', 'Unknown')}]{cost_text}")

def known_target_ids(state):
    """Targets visible to this client: players, battlefield objects, and stack items."""
    result = list(state.get("life_totals", {}))
    result.extend(perm.get("id") for permanents in state.get("battlefield", {}).values()
                  for perm in permanents if perm.get("id"))
    result.extend(item.get("stack_item_id") for item in state.get("stack", [])
                  if item.get("stack_item_id"))
    return result

def visible_mana(state, owner_id):
    pool = state.get("mana_pool", {})
    untapped_lands = [perm.get("id") for perm in state.get("battlefield", {}).get(owner_id, [])
                      if not perm.get("tapped")
                      and cards.get(perm.get("id"), {}).get("card_type") == "Land"]
    pool_text = ", ".join(f"{color}:{amount}" for color, amount in pool.items() if amount) or "empty"
    return pool_text, untapped_lands

def send_pdu(sock, pdu: dict):
    log_pdu("SEND", pdu)
    with send_lock:
        sock.sendall(encode_pdu(pdu))

def recv_exact(sock, n):
    data = b""
    while len(data) < n:
        chunk = sock.recv(n - len(data))
        if not chunk:
            return None
        data += chunk
    return data

def recv_pdu(sock):
    pdu = wire_recv_pdu(sock)
    if pdu is None: return None
    log_pdu("RECV", pdu)
    return pdu

client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client_socket.connect((HOST, PORT))
print(f"[C] Connected to server at {HOST}:{PORT}")

def register_player(sock, input_fn=input, output_fn=print):
    """Register a non-empty, lobby-unique player name.

    The server owns the lobby, so only it can determine whether another client
    already uses a name.  A duplicate response therefore keeps this connection
    open and asks the joining player for a replacement name.
    """
    while True:
        player_name = prompt_until(
            "Enter player name: ",
            lambda value: nonempty(value, "player name", 64),
            input_fn=input_fn,
            output_fn=output_fn,
        )
        send_pdu(sock, {
            "type": "PLAYER_READY",
            "seq_num": 1,
            "player_id": player_name,
            "deck_list": deck_list,
        })
        reply = recv_pdu(sock)
        if reply is None:
            return None, None
        if reply.get("type") == "ERROR" and reply.get("code") == "DUPLICATE_ID":
            output_fn("Name already taken. Please enter a different name.")
            continue
        return player_name, reply

player_id, pending_reply = register_player(client_socket)
if player_id is None:
    raise SystemExit("[C] Server disconnected during player registration.")
print("[C] Ready state accepted.\n")

def receiver():
    """Receive continuously so PONG is processed even during an input prompt."""
    while not stop_event.is_set():
        try:
            pdu = recv_pdu(client_socket)
        except (OSError, ValueError, UnicodeDecodeError, json.JSONDecodeError):
            pdu = None
        if pdu is None:
            incoming_pdus.put(None)
            return
        if pdu.get("type") == "PONG":
            with pong_lock:
                event = pending_pongs.get(pdu.get("seq_num"))
            if event is not None:
                event.set()
            # recv_pdu already prints this PDU in verbose mode. Keep normal
            # gameplay quiet; PONG is connection maintenance, not a game event.
            continue
        incoming_pdus.put(pdu)

def heartbeat():
    """Send PING every 30 seconds and require its matching PONG within 10."""
    seq = 1
    while not stop_event.wait(PING_INTERVAL_SECONDS):
        seq += 1
        pong_received = threading.Event()
        with pong_lock:
            pending_pongs[seq] = pong_received
        try:
            send_pdu(client_socket, {"type": "PING", "seq_num": seq,
                                     "timestamp": int(time.time() * 1000)})
        except OSError:
            stop_event.set()
            incoming_pdus.put(None)
            return
        if not pong_received.wait(PONG_TIMEOUT_SECONDS):
            print(f"[C] No matching PONG within {PONG_TIMEOUT_SECONDS} seconds; disconnecting.")
            stop_event.set()
            try:
                client_socket.shutdown(socket.SHUT_RDWR)
            except OSError:
                pass
            incoming_pdus.put(None)
            return
        with pong_lock:
            pending_pongs.pop(seq, None)

threading.Thread(target=receiver, daemon=True).start()
threading.Thread(target=heartbeat, daemon=True).start()

mulligan_count = 0  # tracks how many times we've mulliganed, used to size cards_to_bottom
latest_state = {}
announced_starting_player = None

# main event loop
while True:
    if pending_reply is not None:
        reply, pending_reply = pending_reply, None
    else:
        reply = incoming_pdus.get()

    if reply is None:
        print("[C] Server disconnected.")
        break

    msg_type = reply.get("type")

    if msg_type == "GAME_STATE_UPDATE":
        state = reply.get("state", {})
        latest_state = state
        phase = state.get("phase")

        print(f"\n=== {state.get('phase')} ===")

        if state.get("phase") == "LOBBY":
            print(f"Players Ready: {state['players_ready']}")
            print(f"Waiting For: {state['waiting_for']}")

        elif state.get("phase") == "MULLIGAN":
            starting_player = state.get("active_player")
            if announced_starting_player != starting_player:
                print(f"\n[GAME] {starting_player} was randomly selected to go first.")
                announced_starting_player = starting_player
            print(f"Turn: {state['turn']}")
            print(f"Active Player: {state['active_player']}")
            print(f"Life Totals: {state['life_totals']}")
            print(f"My Hand: {state['hand']}")
            print(f"Hand Counts: {state['hand_counts']}")
            print(f"Library Counts: {state['library_counts']}")
            print(f"Battlefield: {state['battlefield']}")
            print(f"Graveyard: {state['graveyard']}")
            print(f"Stack: {state['stack']}")

            # Prompt for this player's mulligan decision and send MULLIGAN_CHOICE.
            # seq_num echoes this GAME_STATE_UPDATE's seq_num, per RFC 5.4.
            decision = prompt_until("Keep this hand? (y = keep / n = mulligan): ",
                                    lambda x: choice(x,("y","n"),"mulligan choice"))

            if decision == "y":
                cards_to_bottom = []
                if mulligan_count > 0:
                    print(f"You mulliganed {mulligan_count} time(s); "
                          f"choose {mulligan_count} card(s) to bottom from your hand.")
                    available=list(state["hand"])
                    for i in range(mulligan_count):
                        card = prompt_until(f"  Card {i+1} to bottom: ",
                            lambda x, available=available: nonempty(x,"card ID") if x.strip() in available else (_ for _ in ()).throw(ValueError("card must be a remaining card in your hand")))
                        cards_to_bottom.append(card)
                        available.remove(card)

                send_pdu(client_socket, {
                    "type": "MULLIGAN_CHOICE",
                    "seq_num": reply["seq_num"],
                    "keep": True,
                    "cards_to_bottom": cards_to_bottom
                })
            else:
                mulligan_count += 1
                send_pdu(client_socket, {
                    "type": "MULLIGAN_CHOICE",
                    "seq_num": reply["seq_num"],
                    "keep": False,
                    "cards_to_bottom": []
                })

        elif state.get("phase") == "IN_GAME":
            step = state.get("step")
            hand = state.get("hand", [])
            print(f"Turn: {state.get('turn')} | Active Player: {state.get('active_player')} | Step: {step}")
            print(f"Life: {state.get('life_totals')} | Hand: {hand}")

            # Hand Size Enforcement during Cleanup Step (RFC 7.8)
            if step == "CLEANUP" and state.get("active_player") == player_id and len(hand) > 7:
                excess = len(hand) - 7
                print(f"\n[CLEANUP] Your hand size exceeds 7! You must discard {excess} card(s).")
                discard_list = []
                available=list(hand)
                for i in range(excess):
                    card = prompt_until(f"  Card {i+1} ID to discard: ",
                        lambda x, available=available: nonempty(x,"card ID") if x.strip() in available else (_ for _ in ()).throw(ValueError("card must be a remaining card in your hand")))
                    discard_list.append(card)
                    available.remove(card)

                send_pdu(client_socket, {
                    "type": "DISCARD",
                    "seq_num": reply["seq_num"],  # Echo last GAME_STATE_UPDATE seq_num
                    "card_ids": discard_list
                })

    elif msg_type == "PRIORITY_GRANT":
        print(f"\n[PRIORITY] You have priority (seq_num: {reply.get('seq_num')}).")
        # New servers include the step in PRIORITY_GRANT.  The state fallback
        # keeps the client compatible with an older server during upgrades.
        step = reply.get("step") or latest_state.get("step")
        active_player = latest_state.get("active_player")
        print(f"Current turn: {active_player} | Step: {step}")
        show_cards("Your hand", latest_state.get("hand", []))
        pool_text, untapped_lands = visible_mana(latest_state, player_id)
        print(f"Mana pool: {pool_text} | Untapped lands available: {len(untapped_lands)}")
        if untapped_lands:
            print(f"\nUntapped lands ({len(untapped_lands)}):")
            # Get your battlefield list from latest_state
            my_battlefield = latest_state.get("battlefield", {}).get(player_id, [])
            perm_dict = {p.get("id"): p for p in my_battlefield if isinstance(p, dict)}
            
            for land_id in untapped_lands:
                card_data = cards.get(land_id, {})
                perm_state = perm_dict.get(land_id, {})
                print(f"  {format_land_display(land_id, card_data, perm_state)}")
        while True:
            action = prompt_until("Action? p=pass, l=land, s=spell, x=ability, c=concede: ",
                                  lambda x: choice(x,("p","l","s","x","c"),"action"))

            if action == "c":
                send_pdu(client_socket, {"type": "CONCEDE", "seq_num": reply.get("seq_num")})
                break

            if action == "p":
                send_pdu(client_socket, {"type": "PRIORITY_PASS", "seq_num": reply.get("seq_num")})
                break

            hand = latest_state.get("hand", [])

            if action == "l":
                if latest_state.get("land_played_this_turn"):
                    print("You already played a land this turn. Choose another action.")
                    continue
                if active_player != player_id:
                    print(f"Cannot play a land now. It is {active_player}'s turn; wait for your own main phase.")
                    continue
                if step not in ("PRECOMBAT_MAIN", "POSTCOMBAT_MAIN"):
                    print(f"Cannot play a land during {step}. Wait for PRECOMBAT_MAIN or POSTCOMBAT_MAIN.")
                    continue
                legal = [cid for cid in hand if cards.get(cid, {}).get("card_type") == "Land"]
                if not legal:
                    print("No land in your hand. Choose another action.")
                    continue
                show_cards("Lands you can play", legal)
                land_id = prompt_until("Land card ID: ",
                    lambda x: nonempty(x,"land ID") if x.strip() in legal else (_ for _ in ()).throw(ValueError("choose a Land from your displayed hand")))
                send_pdu(client_socket, {"type":"PLAY_LAND", "seq_num":reply["seq_num"], "card_id":land_id})
                break

            if action == "s":
                own_main_phase = (latest_state.get("active_player") == player_id
                                  and step in ("PRECOMBAT_MAIN", "POSTCOMBAT_MAIN")
                                  and not latest_state.get("stack"))
                legal = [cid for cid in hand
                         if cards.get(cid, {}).get("card_type") == "Instant"
                         or (own_main_phase and cards.get(cid, {}).get("card_type") != "Land")]
                if not legal:
                    if any(cards.get(cid, {}).get("card_type") != "Land" for cid in hand):
                        print("You cannot cast those spells now. Creatures and sorceries require your main phase.")
                    else:
                        print("No spell in your hand. Choose another action.")
                    continue
                show_cards("Spells allowed by timing (mana cost still applies)", legal)
                card_id = prompt_until("Spell card ID: ",
                    lambda x: nonempty(x,"spell ID") if x.strip() in legal else (_ for _ in ()).throw(ValueError("choose a displayed spell that can be cast now")))
                valid_targets = known_target_ids(latest_state)
                print("Valid target IDs: " + (", ".join(valid_targets) if valid_targets else "none"))
                targets = prompt_until("Target IDs (comma-separated, blank for none): ",
                    lambda x: (lambda selected: selected if all(t in valid_targets for t in selected)
                               else (_ for _ in ()).throw(ValueError(
                                   "unknown target ID(s): " + ", ".join(t for t in selected if t not in valid_targets))))
                              (csv_ids(x,"target IDs")))
                cost=cards[card_id].get("cost",{}); payment={k:int(cost.get(k) or 0) for k in "WUBRG"}
                payment["X"]=int(cost.get("Generic") or 0)
                send_pdu(client_socket, {"type":"CAST_SPELL", "seq_num":reply["seq_num"],
                                         "card_id":card_id, "targets":targets, "mana_payment":payment})
                break

            battlefield = latest_state.get("battlefield", {}).get(player_id, [])
            legal = [perm.get("id") for perm in battlefield
                     if not perm.get("tapped")
                     and cards.get(perm.get("id"), {}).get("card_name") in SUPPORTED_ABILITIES]
            if not legal:
                print("No usable ability on your battlefield. Abilities do not come from cards in your hand.")
                continue
            show_cards("Permanents with usable abilities", legal)
            source = prompt_until("Permanent/source ID: ",
                lambda x: nonempty(x,"source ID") if x.strip() in legal else (_ for _ in ()).throw(ValueError("choose an untapped permanent with a usable ability")))
            valid_targets = known_target_ids(latest_state)
            print("Valid target IDs: " + (", ".join(valid_targets) if valid_targets else "none"))
            targets = prompt_until("Target IDs (comma-separated, blank for none): ",
                lambda x: (lambda selected: selected if all(t in valid_targets for t in selected)
                           else (_ for _ in ()).throw(ValueError(
                               "unknown target ID(s): " + ", ".join(t for t in selected if t not in valid_targets))))
                          (csv_ids(x,"target IDs")))
            send_pdu(client_socket, {"type":"ACTIVATE_ABILITY", "seq_num":reply["seq_num"],
                                     "source_id":source, "ability_index":0, "targets":targets,
                                     "cost_payment":{"tap":True,"mana":{}}})
            break

    elif msg_type == "PHASE_TRANSITION":
        print(f"\n=== PHASE_TRANSITION: {reply.get('from_phase')} -> {reply.get('to_phase')} "
              f"(turn {reply.get('turn')}, active: {reply.get('active_player')}) ===")
        to_step = reply.get("to_phase"); is_active = reply.get("active_player") == player_id
        if not is_active and to_step in ("UPKEEP", "DRAW", "PRECOMBAT_MAIN", "BEGIN_COMBAT",
                                         "END_OF_COMBAT", "POSTCOMBAT_MAIN", "END_STEP"):
            print(f"[WAITING] {reply.get('active_player')} is the active player and must act first.")
        if to_step == "DECLARE_ATTACKERS" and is_active:
            opponents=[x for x in latest_state.get("life_totals",{}) if x!=player_id]
            opponent = prompt_until("Defending player ID: ",lambda x:nonempty(x,"player ID") if x.strip() in opponents else (_ for _ in ()).throw(ValueError("choose the opposing player ID")))
            own={x.get("id"):x for x in latest_state.get("battlefield",{}).get(player_id,[])}
            show_cards("Your battlefield creatures", [cid for cid in own if cards.get(cid,{}).get("card_type")=="Creature"])
            ids = prompt_until("Attacker IDs (comma-separated, blank for none): ",lambda x:csv_ids(x,"attacker IDs"))
            while any(cid not in own or cards.get(cid,{}).get("card_type")!="Creature" or own[cid].get("tapped") for cid in ids):
                print("Invalid input: choose unique, untapped creatures you control.")
                ids=prompt_until("Attacker IDs: ",lambda x:csv_ids(x,"attacker IDs"))
            send_pdu(client_socket,{"type":"DECLARE_ATTACKERS","seq_num":reply["seq_num"],
                                    "attackers":[{"creature_id":x,"target":opponent} for x in ids]})
        elif to_step == "DECLARE_BLOCKERS" and not is_active:
            own={x.get("id"):x for x in latest_state.get("battlefield",{}).get(player_id,[])}
            show_cards("Your available battlefield creatures", [cid for cid,perm in own.items() if cards.get(cid,{}).get("card_type")=="Creature" and not perm.get("tapped")])
            parsed=prompt_until("Blocks as blocker:attacker pairs (comma-separated, blank for none): ",lambda x:pairs(x,"block"))
            while any(blocker not in own or cards.get(blocker,{}).get("card_type")!="Creature" or own[blocker].get("tapped") for blocker,_ in parsed):
                print("Invalid input: each blocker must be an untapped creature you control.")
                parsed=prompt_until("Blocks: ",lambda x:pairs(x,"block"))
            send_pdu(client_socket,{"type":"DECLARE_BLOCKERS","seq_num":reply["seq_num"],
                                    "blockers":[{"creature_id":b,"blocking_id":a} for b,a in parsed]})
        elif to_step == "ASSIGN_DAMAGE_ORDER" and is_active:
            attacker=prompt_until("Multiply-blocked attacker ID: ",lambda x:nonempty(x,"attacker ID"))
            order=prompt_until("Blocker order (comma-separated): ",lambda x:csv_ids(x,"blocker order",False))
            send_pdu(client_socket,{"type":"ASSIGN_DAMAGE_ORDER","seq_num":reply["seq_num"],
                                    "attacker_id":attacker,"blocker_order":order})

    elif msg_type == "GAME_OVER":
        # NEW: Game Over Notification (RFC Section 6.6)
        print(f"\n==========================================")
        print(f" GAME OVER!")
        print(f" Winner: {reply.get('winner_id')}")
        print(f" Reason: {reply.get('reason')}")
        print(f"==========================================\n")
        
        # Reset local state for the next match
        mulligan_count = 0
        announced_starting_player = None
        replay = prompt_until("Play another game on this connection? (y/n): ",
                              lambda x: choice(x, ("y", "n"), "replay choice"))
        if replay == "n":
            print("[C] Leaving the lobby.")
            break
        deck_list = build_random_deck(cards)
        send_pdu(client_socket, {
            "type": "PLAYER_READY",
            "seq_num": reply.get("seq_num", 1),
            "player_id": player_id,
            "deck_list": deck_list,
        })
        print("[C] Ready for a new game. Waiting for the other player...")

    elif msg_type == "TRIGGER_ORDER":
        offered = reply.get("trigger_ids", [])
        print("Simultaneous triggers:", offered)
        order = prompt_until("Trigger IDs in desired order (comma-separated): ",
            lambda x: csv_ids(x,"trigger IDs",False) if set(csv_ids(x,"trigger IDs",False))==set(offered) and len(csv_ids(x,"trigger IDs",False))==len(offered) else (_ for _ in ()).throw(ValueError("order must contain every offered trigger exactly once")))
        send_pdu(client_socket, {"type":"TRIGGER_ORDER_RESPONSE", "seq_num":reply["seq_num"], "ordered_trigger_ids":order})

    elif msg_type == "TRIGGER_CHOICE":
        accept = prompt_until("Use trigger? (y/n): ",lambda x:choice(x,("y","n"),"trigger choice"))=="y"
        legal=reply.get("legal_targets",[]); required=reply.get("requires_target",False)
        target = None
        if accept and required:
            target=prompt_until("Chosen target: ",lambda x:nonempty(x,"target") if x.strip() in legal else (_ for _ in ()).throw(ValueError("choose one of the listed legal targets")))
        send_pdu(client_socket, {"type":"TRIGGER_CHOICE_RESPONSE", "seq_num":reply["seq_num"],
                                 "trigger_id":reply.get("trigger_id"), "accept":accept, "chosen_target":target})

    elif msg_type == "ERROR":
        print(f"[ERROR] {reply['code']}: {reply['message']}")

    else:
        print(f"[C] Received: {reply}")

stop_event.set()
client_socket.close()
print("[C] Socket closed")
