import socket
import json
import struct
import threading
import random
import argparse
import datetime

HOST = "127.0.0.1"
PORT = 4444

# --- verbose mode setup ---
# Parse --verbose / -v at startup. VERBOSE is a module-level flag that every
# send_pdu/recv_pdu call checks before printing. Toggled only via the CLI flag
# for now (RFC just requires it be toggleable at runtime via startup argument).
parser = argparse.ArgumentParser(description="MTGNP Game Server")
parser.add_argument("-v", "--verbose", action="store_true",
                     help="Print every PDU sent/received to the console")
args = parser.parse_args()
VERBOSE = args.verbose

def log_pdu(direction: str, peer_label: str, pdu: dict):
    """Print a clearly-labelled, readable line for every PDU when verbose mode is on.
    direction: 'SEND' or 'RECV'
    peer_label: human-readable identifier for the other end (e.g. 'player_1' or address tuple)
    """
    if not VERBOSE:
        return
    timestamp = datetime.datetime.now().strftime("%H:%M:%S.%f")[:-3]
    label = f"S->{peer_label}" if direction == "SEND" else f"{peer_label}->S"
    print(f"[VERBOSE {timestamp}] [{label}] {json.dumps(pdu)}")

# global game_phase
game_phase = "LOBBY"
# server seq num
server_seq_num = 0

# --- turn / priority state (populated once IN_GAME begins, see begin_turn()) ---
turn_number = 0
current_step = None      # e.g. "UPKEEP", "DRAW", "PRECOMBAT_MAIN", ...
active_conn = None        # connection of the Active Player (AP) this turn
priority_conn = None       # connection that currently holds priority
priority_seq_num = None    # seq_num the priority holder must echo in PRIORITY_PASS
consecutive_passes = 0     # how many players have passed in a row in this window
stack = []                  # shared LIFO stack (empty until CAST_SPELL exists)

# Step order used by advance_step(). Combat's sub-steps (Section 9) aren't
# implemented yet, so PRECOMBAT_MAIN currently skips straight to
# POSTCOMBAT_MAIN — TODO: insert BEGIN_COMBAT..END_OF_COMBAT here later.
STEP_SEQUENCE = {
    "UPKEEP": "DRAW",
    "DRAW": "PRECOMBAT_MAIN",
    "PRECOMBAT_MAIN": "POSTCOMBAT_MAIN",
    "POSTCOMBAT_MAIN": "END_STEP",
    "END_STEP": "CLEANUP",
}
# Steps that open a priority window (all of Section 7's steps except UNTAP
# and CLEANUP, which never grant priority per the RFC).
PRIORITY_STEPS = {"UPKEEP", "DRAW", "PRECOMBAT_MAIN", "POSTCOMBAT_MAIN", "END_STEP"}

server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
server_socket.bind((HOST, PORT))
server_socket.listen(5)
print(f"[S] Listening on {HOST}:{PORT}")

# load card catalog — keyed by individual card INSTANCE id (e.g. "mountain_001"),
# not base card name. Generated by build_catalog.py from mtgnp_master_card_list.xlsx.
# This is the shared out-of-band catalog referenced in RFC Section 1.
with open("card_instances.json", "r") as f:
    cards = json.load(f)

connected_clients = []       
players = {}                 
lock = threading.Lock()  # to protect shared state

def get_peer_label(sock):
    """Prefer the player_id if this connection has registered one; fall back to address."""
    info = players.get(sock)
    if info and info.get("player_id"):
        return info["player_id"]
    try:
        addr = sock.getpeername()
        return f"{addr[0]}:{addr[1]}"
    except OSError:
        return "unknown"

def send_pdu(sock, pdu: dict): #to send a PDU to the socket
    log_pdu("SEND", get_peer_label(sock), pdu)
    payload = json.dumps(pdu).encode("utf-8")
    length_prefix = struct.pack(">I", len(payload)) 
    sock.sendall(length_prefix + payload)

def recv_exact(sock, n): #to recv exact n bytes from socket
    data = b""
    while len(data) < n:
        chunk = sock.recv(n - len(data))
        if not chunk:
            return None
        data += chunk
    return data

def recv_pdu(sock):
    length_bytes = recv_exact(sock, 4)
    if length_bytes is None:
        return None
    length = struct.unpack(">I", length_bytes)[0]
    payload = recv_exact(sock, length)
    if payload is None:
        return None
    pdu = json.loads(payload.decode("utf-8"))
    log_pdu("RECV", get_peer_label(sock), pdu)
    return pdu

def broadcast_lobby_status():
    global server_seq_num
    """Send every ready player an updated GAME_STATE_UPDATE (lobby variant)."""
    with lock:
        ready_ids = [p["player_id"] for p in players.values()]
        snapshot_conns = list(players.keys())
    all_ids = ["player_1", "player_2"]
    waiting_for = [pid for pid in all_ids if pid not in ready_ids]

    for conn in snapshot_conns:
        server_seq_num += 1

        send_pdu(conn, {
            "type": "GAME_STATE_UPDATE",
            "seq_num": server_seq_num,
            "state": {
                "phase": "LOBBY",
                "players_ready": len(players),
                "waiting_for": waiting_for
            }
        })

def handle_player_ready(conn, pdu):
    global game_phase

    if game_phase != "LOBBY":
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 1),
            "code": "INVALID_STATE",
            "message": "PLAYER_READY is only allowed while in the LOBBY."
        })
        return
    
    player_id = pdu.get("player_id")
    deck_list = pdu.get("deck_list")

    # Validate deck list format
    if not isinstance(deck_list, list) or len(deck_list) < 1 or len(deck_list) > 50:
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 1),
            "code": "ILLEGAL_DECK",
            "message": f"Deck contains {len(deck_list) if isinstance(deck_list, list) else 0} cards; must be 1-50."
        })
        return

    # Validate card IDs
    illegal_cards = [card_id for card_id in deck_list if card_id not in cards]
    if illegal_cards:
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 1),
            "code": "ILLEGAL_DECK",
            "message": f"Unknown card IDs: {', '.join(illegal_cards)}"
        })
        return

    # Validate duplicates
    if len(deck_list) != len(set(deck_list)):
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 1),
            "code": "ILLEGAL_DECK",
            "message": "Duplicate card instance(s) in deck."
        })
        return

    should_start_setup = False
    with lock:
        # Check duplicate ID across existing connections
        for other_conn, other_info in players.items():
            if other_conn != conn and other_info["player_id"] == player_id:
                send_pdu(conn, {
                    "type": "ERROR",
                    "seq_num": pdu.get("seq_num", 1),
                    "code": "DUPLICATE_ID",
                    "message": f"player_id '{player_id}' is already taken."
                })
                return

        # Add or update player outside of the loop
        if conn in players:
            players[conn]["player_id"] = player_id
            players[conn]["deck_list"] = deck_list
            print(f"[S] {player_id} updated their deck ({len(deck_list)} cards)")
        else:
            players[conn] = {
                "player_id": player_id,
                "deck_list": deck_list,
                "library": [],
                "hand": [],
                "life": 20,
                "mulligan_count": 0,
                "kept": False,
                "last_state_seq_num": None,
                "battlefield": [],
                "graveyard": [],
                "land_played_this_turn": False,
                "connected": True,
                "reconnect_timer": None
            }
            print(f"[S] {player_id} is ready with {len(deck_list)} cards ({len(players)}/2)")

        if len(players) == 2 and game_phase == "LOBBY":
            game_phase = "GAME_SETUP"
            should_start_setup = True

    broadcast_lobby_status()

    if should_start_setup:
        print("[S] Both players ready — transitioning to GAME_SETUP")
        start_game_setup()

def get_starting_player_id():
    """Look up which player was chosen to go first (set once in start_game_setup)."""
    for info in players.values():
        if info.get("is_starting_player"):
            return info["player_id"]
    return None

def get_starting_conn():
    """Same as get_starting_player_id but returns the connection object."""
    for conn, info in players.items():
        if info.get("is_starting_player"):
            return conn
    return None

def get_other_conn(conn):
    """Given one player's connection, return the opponent's connection."""
    for c in players:
        if c != conn:
            return c
    return None

def build_personalized_mulligan_state(player):
    """Build the MULLIGAN-phase state object personalized for one player.
    Used both for the initial post-setup broadcast and for post-redraw updates."""
    return {
        "turn": 0,
        "phase": "MULLIGAN",
        "active_player": get_starting_player_id(),
        "life_totals": {
            info["player_id"]: info["life"]
            for info in players.values()
        },
        "hand": player["hand"],
        "hand_counts": {
            info["player_id"]: len(info["hand"])
            for info in players.values()
            if info is not player
        },
        "library_counts": {
            info["player_id"]: len(info["library"])
            for info in players.values()
        },
        "battlefield": {
            info["player_id"]: info["battlefield"]
            for info in players.values()
        },
        "graveyard": {
            info["player_id"]: info["graveyard"]
            for info in players.values()
        },
        "stack": []
    }

def build_ingame_state(player):
    """Build the IN_GAME-phase state object personalized for one player
    (RFC Section 10.2.2, in-game variant)."""
    return {
        "turn": turn_number,
        "phase": current_step,
        "active_player": players[active_conn]["player_id"],
        "priority_holder": players[priority_conn]["player_id"] if priority_conn else None,
        "life_totals": {
            info["player_id"]: info["life"]
            for info in players.values()
        },
        "stack": stack,
        "battlefield": {
            info["player_id"]: info["battlefield"]
            for info in players.values()
        },
        "graveyard": {
            info["player_id"]: info["graveyard"]
            for info in players.values()
        },
        "hand": player["hand"],
        "hand_counts": {
            info["player_id"]: len(info["hand"])
            for info in players.values()
            if info is not player
        },
        "library_counts": {
            info["player_id"]: len(info["library"])
            for info in players.values()
        },
        "land_played_this_turn": player["land_played_this_turn"]
    }

def broadcast_ingame_state():
    """Send every player a personalized IN_GAME GAME_STATE_UPDATE."""
    global server_seq_num

    # check for state-based win/loss conditions
    if check_life_totals():
        return #trigger_game_over() is called
    
    for conn, player in list(players.items()):
        server_seq_num += 1
        send_pdu(conn, {
            "type": "GAME_STATE_UPDATE",
            "seq_num": server_seq_num,
            "state": build_ingame_state(player)
        })

def start_game_setup():
    global game_phase
    global server_seq_num

    print("[S] Starting GAME_SETUP")

    with lock:
        #initialize player life to 20
        for player in players.values():
            player["life"] = 20

        # shuffle deck
        for player in players.values():
            player["library"] = player["deck_list"][:]
            random.shuffle(player["library"])

        # draw seven cards
        for player in players.values():
            player["hand"] = []

            while player["library"] and len(player["hand"]) < 7:
                player["hand"].append(player["library"].pop())

        # choose player to start
        starting_conn = random.choice(list(players.keys()))

        for conn, player in players.items():
            player["is_starting_player"] = (conn == starting_conn)

        # Flip to MULLIGAN before sending, since a fast client could otherwise reply
        # before the server considers itself out of GAME_SETUP.
        game_phase = "MULLIGAN"

        # send personalized game state update to each player
        for conn, player in players.items():
            server_seq_num += 1
            player["last_state_seq_num"] = server_seq_num

            send_pdu(conn, {
                "type": "GAME_STATE_UPDATE",
                "seq_num": server_seq_num,
                "state": build_personalized_mulligan_state(player)
            })

    print("[S] Transitioned to MULLIGAN")

def redraw_hand(player):
    """London Mulligan redraw: shuffle hand back into library, reshuffle, draw a fresh 7."""
    player["library"].extend(player["hand"])
    player["hand"] = []
    random.shuffle(player["library"])
    while player["library"] and len(player["hand"]) < 7:
        player["hand"].append(player["library"].pop())

def check_mulligan_complete():
    """If both players have kept, transition to IN_GAME and start Turn 1's Untap Step.
    Caller must hold `lock`."""
    global game_phase

    if len(players) != 2 or not all(info.get("kept") for info in players.values()):
        return

    game_phase = "IN_GAME"
    print("[S] Both players kept — transitioning to IN_GAME (Turn 1, UNTAP)")
    begin_turn(get_starting_conn(), 1, from_phase="MULLIGAN")

def begin_turn(conn, turn_num, from_phase):
    """Starts a new turn for `conn` as the Active Player.
    Performs the Untap Step (RFC 7.2) — untap AP's permanents, reset the
    land-per-turn flag — then auto-advances into Upkeep (Untap never opens
    a priority window)."""
    global active_conn, turn_number, current_step, server_seq_num

    active_conn = conn
    turn_number = turn_num
    current_step = "UNTAP"

    player = players[active_conn]

    # Untap: no permanents exist yet (battlefield isn't populated until
    # PLAY_LAND / CAST_SPELL land support is added), so this loop is a no-op
    # for now — but it's exactly where untap logic goes once permanents exist.
    for permanent in player["battlefield"]:
        permanent["tapped"] = False
    player["land_played_this_turn"] = False

    server_seq_num += 1
    for c in list(players.keys()):
        send_pdu(c, {
            "type": "PHASE_TRANSITION",
            "seq_num": server_seq_num,
            "from_phase": from_phase,
            "to_phase": "UNTAP",
            "active_player": player["player_id"],
            "turn": turn_num
        })

    # broadcast the untaapped state to both players (RFC 7.2)
    broadcast_ingame_state()

    print(f"[S] Turn {turn_num} — {player['player_id']} untaps")

    # UNTAP never opens a priority window — go straight to UPKEEP.
    current_step = "UPKEEP"
    server_seq_num += 1
    for c in list(players.keys()):
        send_pdu(c, {
            "type": "PHASE_TRANSITION",
            "seq_num": server_seq_num,
            "from_phase": "UNTAP",
            "to_phase": "UPKEEP",
            "active_player": player["player_id"],
            "turn": turn_num
        })
    enter_step("UPKEEP")

def enter_step(step_name):
    """Perform any automatic server-side actions for entering a step, then
    open a priority window if this step grants one (RFC Section 7)."""
    global current_step
    current_step = step_name

    if step_name == "DRAW":
        do_draw_step()
        if game_phase != "IN_GAME":
            return  # do_draw_step() may have ended the game (empty-library loss)

    if step_name == "CLEANUP":
        do_cleanup_step()
        return

    if step_name in PRIORITY_STEPS:
        open_priority_window()

def do_draw_step():
    """RFC 7.4: AP draws one card, except the first player's very first turn."""
    player = players[active_conn]
    skip_draw = (turn_number == 1 and player.get("is_starting_player"))

    if not skip_draw:
        if not player["library"]:
            # RFC 6.5: being required to draw from an empty library is a loss.
            trigger_game_over(get_other_conn(active_conn), "DECK_EMPTY")
            return
        player["hand"].append(player["library"].pop())

    broadcast_ingame_state()

def open_priority_window():
    """Opens a priority window for the current step, giving the Active
    Player priority first (RFC Section 8.1, rule 1)."""
    global consecutive_passes
    consecutive_passes = 0
    grant_priority(active_conn)

def grant_priority(conn):
    """Send PRIORITY_GRANT to `conn` and record the seq_num it must echo
    when it responds (PRIORITY_PASS, CAST_SPELL, etc. — RFC Section 5.4/8.5)."""
    global priority_conn, priority_seq_num, server_seq_num
    priority_conn = conn
    server_seq_num += 1
    priority_seq_num = server_seq_num
    send_pdu(conn, {
        "type": "PRIORITY_GRANT",
        "player_id": players[conn]["player_id"],
        "seq_num": server_seq_num,
        "time_limit_ms": 60000
    })

def advance_step():
    """Called when both players have passed priority consecutively with an
    empty stack (RFC Section 8.1, rule 6). Moves to the next step per the
    Section 7 turn structure, or starts the next player's turn at CLEANUP."""
    global server_seq_num

    next_step = STEP_SEQUENCE.get(current_step)
    if next_step is None:
        return  # only CLEANUP has no "next" here; handled by do_cleanup_step

    old_step = current_step
    server_seq_num += 1
    for conn in list(players.keys()):
        send_pdu(conn, {
            "type": "PHASE_TRANSITION",
            "seq_num": server_seq_num,
            "from_phase": old_step,
            "to_phase": next_step,
            "active_player": players[active_conn]["player_id"],
            "turn": turn_number
        })

    enter_step(next_step)

def do_cleanup_step():
    """RFC 7.8: Remove damage, clear until-end-of-turn effects, enforce maximum
    hand size (7 cards), and start the next player's turn."""
    active_player = players[active_conn]
    print(f"[S] Cleanup — turn {turn_number} ends for {active_player['player_id']}")

    # Check maximum hand size requirement (RFC 7.8)
    if len(active_player["hand"]) > 7:
        print(f"[S] {active_player['player_id']} has {len(active_player['hand'])} cards; awaiting DISCARD PDU(s)...")
        # Send an updated state to the AP so they have the seq_num to echo in DISCARD
        global server_seq_num
        server_seq_num += 1
        active_player["last_state_seq_num"] = server_seq_num
        send_pdu(active_conn, {
            "type": "GAME_STATE_UPDATE",
            "seq_num": server_seq_num,
            "state": build_ingame_state(active_player)
        })
        return  # Pause and wait for handle_discard

    finish_cleanup_step()

def finish_cleanup_step():
    """Clear end-of-turn state and advance to the next player's Untap Step."""
    # Remove all damage from creatures and clear "until end of turn" effects
    for player in players.values():
        for permanent in player["battlefield"]:
            permanent["damage"] = 0  # Ready for when damage/creatures are added
            # clear "until end of turn" temporary modifiers here when implemented

    # Broadcast updated game state reflecting the cleared state
    broadcast_ingame_state()

    # Increment turn counter, switch Active Player, and begin Untap Step
    next_conn = get_other_conn(active_conn)
    begin_turn(next_conn, turn_number + 1, from_phase="CLEANUP")

def check_life_totals():
    """Checks if any player's life total has reached <= 0 (RFC 6.5)."""
    if game_phase != "IN_GAME":
        return False

    dead_players = [conn for conn, info in players.items() if info["life"] <= 0]
    if dead_players:
        # If one player drops <= 0, the other wins
        for conn in list(players.keys()):
            if conn not in dead_players:
                trigger_game_over(conn, "LIFE_ZERO")
                return True
    return False

def trigger_game_over(winner_conn, reason):
    """Broadcast GAME_OVER and return to LOBBY (RFC Section 6.6)."""
    global game_phase, server_seq_num, turn_number, current_step
    winner_id = players[winner_conn]["player_id"]
    loser_conn = get_other_conn(winner_conn)
    loser_id = players[loser_conn]["player_id"] if loser_conn else None

    # cancel any running reconnect timers
    for info in players.values():
        if info.get("reconnect_timer"):
            info["reconnect_timer"].cancel()
            info["reconnect_timer"] = None

    for conn in list(players.keys()):
        if players[conn].get("connected", True):
            server_seq_num += 1
            send_pdu(conn, {
                "type": "GAME_OVER",
                "seq_num": server_seq_num,
                "winner_id": winner_id,
                "loser_id": loser_id,
                "reason": reason
            })

    print(f"[S] GAME_OVER — {winner_id} wins ({reason})")

    # reset internal game state variables
    game_phase = "LOBBY"
    turn_number = 0
    current_step = None
    stack.clear()

    # reset player-specific game state for remaining connections
    for player_info in players.values():
        player_info["library"] = []
        player_info["hand"] = []
        player_info["battlefield"] = []
        player_info["graveyard"] = []
        player_info["life"] = 20
        player_info["mulligan_count"] = 0
        player_info["kept"] = False
        player_info["is_starting_player"] = False
        player_info["land_played_this_turn"] = False

    # Notify remaining clients of returning to LOBBY
    broadcast_lobby_status()
    

def handle_priority_pass(conn, pdu):
    """Handle a PRIORITY_PASS PDU (RFC Section 8.2)."""
    global consecutive_passes

    if game_phase != "IN_GAME":
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 0),
            "code": "WRONG_PHASE",
            "message": "PRIORITY_PASS is only valid during IN_GAME.",
            "rejected_action": pdu
        })
        return

    with lock:
        if conn != priority_conn:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "NOT_YOUR_PRIORITY",
                "message": "You do not currently hold priority.",
                "rejected_action": pdu
            })
            return

        if pdu.get("seq_num") != priority_seq_num:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "STALE_ACTION",
                "message": f"Priority token mismatch. Expected seq_num {priority_seq_num}, got {pdu.get('seq_num')}.",
                "rejected_action": pdu
            })
            return

        consecutive_passes += 1
        print(f"[S] {players[conn]['player_id']} passes priority ({consecutive_passes}/2)")

        if consecutive_passes >= 2:
            # Both passed consecutively. Stack is always empty for now (no
            # CAST_SPELL yet) — once it exists, check `stack` here and
            # resolve the top item instead of advancing when non-empty
            # (RFC Section 8.1, rule 5 vs rule 6).
            advance_step()
        else:
            grant_priority(get_other_conn(conn))

def handle_play_land(conn, pdu):
    """Handle a PLAY_LAND PDU (RFC Section 7.5 / 10.2.19).
    Sorcery-speed, Active-Player-only, one per turn, doesn't touch the stack.
    The Active Player retains priority afterward (a fresh PRIORITY_GRANT)."""
    if game_phase != "IN_GAME":
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 0),
            "code": "WRONG_PHASE",
            "message": "PLAY_LAND is only valid during IN_GAME.",
            "rejected_action": pdu
        })
        return

    if current_step not in ("PRECOMBAT_MAIN", "POSTCOMBAT_MAIN"):
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 0),
            "code": "WRONG_PHASE",
            "message": "Lands may only be played during a Main Phase.",
            "rejected_action": pdu
        })
        return

    with lock:
        # PLAY_LAND is a priority-bearing PDU (RFC 5.4) — same seq_num/holder
        # rules as PRIORITY_PASS apply.
        if conn != priority_conn:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "NOT_YOUR_PRIORITY",
                "message": "You do not currently hold priority.",
                "rejected_action": pdu
            })
            return

        if pdu.get("seq_num") != priority_seq_num:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "STALE_ACTION",
                "message": f"Priority token mismatch. Expected seq_num {priority_seq_num}, got {pdu.get('seq_num')}.",
                "rejected_action": pdu
            })
            return

        if conn != active_conn:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "ILLEGAL_ACTION",
                "message": "Only the Active Player may play a land.",
                "rejected_action": pdu
            })
            return

        player = players[conn]

        if player["land_played_this_turn"]:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "ILLEGAL_ACTION",
                "message": "You have already played a land this turn.",
                "rejected_action": pdu
            })
            return

        card_id = pdu.get("card_id")

        if card_id not in player["hand"]:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "ILLEGAL_ACTION",
                "message": f"Card '{card_id}' is not in your hand.",
                "rejected_action": pdu
            })
            return

        card_info = cards.get(card_id)
        if card_info is None or card_info.get("card_type") != "Land":
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "ILLEGAL_ACTION",
                "message": f"Card '{card_id}' is not a Land.",
                "rejected_action": pdu
            })
            return

        # Apply: move from hand to battlefield as an untapped permanent.
        player["hand"].remove(card_id)
        player["battlefield"].append({"id": card_id, "tapped": False})
        player["land_played_this_turn"] = True

        print(f"[S] {player['player_id']} plays land {card_id}")

        broadcast_ingame_state()
        # AP retains priority — issue a fresh PRIORITY_GRANT (RFC 7.5).
        open_priority_window()

RECONNECT_TIMEOUT_SEC = 30.0  # Adjust implementation-defined timeout as needed

def handle_reconnect_timeout(player_id):
    """Callback when reconnect timer expires."""
    with lock:
        if game_phase not in ("IN_GAME", "MULLIGAN"):
            return

        # Find the player who timed out
        offending_conn = None
        for conn, info in players.items():
            if info["player_id"] == player_id and not info["connected"]:
                offending_conn = conn
                break

        if offending_conn:
            print(f"[S] Reconnect timer expired for {player_id}.")
            winner_conn = get_other_conn(offending_conn)
            if winner_conn:
                trigger_game_over(winner_conn, "DISCONNECT")


def handle_disconnect(conn):
    """Handle lost connection with a grace period timer."""
    global game_phase
    with lock:
        if conn not in players:
            return

        player_info = players[conn]
        player_info["connected"] = False
        pid = player_info["player_id"]

        if game_phase in ("IN_GAME", "MULLIGAN"):
            print(f"[S] {pid} disconnected. Starting {RECONNECT_TIMEOUT_SEC}s reconnect timer...")
            
            # Start timer thread to wait for reconnection
            timer = threading.Timer(RECONNECT_TIMEOUT_SEC, handle_reconnect_timeout, args=[pid])
            player_info["reconnect_timer"] = timer
            timer.start()
        else:
            # In LOBBY or GAME_OVER, remove connection immediately
            del players[conn]

def handle_mulligan_choice(conn, pdu):
    """Handle a MULLIGAN_CHOICE PDU per RFC Section 6.4."""
    global server_seq_num

    if game_phase != "MULLIGAN":
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 0),
            "code": "WRONG_PHASE",
            "message": "MULLIGAN_CHOICE is only allowed during the MULLIGAN phase.",
            "rejected_action": pdu
        })
        return

    with lock:
        player = players.get(conn)
        if player is None:
            return

        # seq_num must echo the most recently sent GAME_STATE_UPDATE for this player
        expected_seq = player.get("last_state_seq_num")
        if pdu.get("seq_num") != expected_seq:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "STALE_ACTION",
                "message": f"Priority token mismatch. Expected seq_num {expected_seq}, got {pdu.get('seq_num')}.",
                "rejected_action": pdu
            })
            return

        keep = pdu.get("keep")
        cards_to_bottom = pdu.get("cards_to_bottom", [])

        if keep:
            mulligan_count = player["mulligan_count"]

            # cards_to_bottom must contain exactly N card IDs, all currently in hand
            if not isinstance(cards_to_bottom, list) or len(cards_to_bottom) != mulligan_count:
                send_pdu(conn, {
                    "type": "ERROR",
                    "seq_num": pdu.get("seq_num", 0),
                    "code": "ILLEGAL_ACTION",
                    "message": f"cards_to_bottom must contain exactly {mulligan_count} card ID(s); got {len(cards_to_bottom) if isinstance(cards_to_bottom, list) else 'invalid'}.",
                    "rejected_action": pdu
                })
                return

            hand_check = list(player["hand"])
            for card_id in cards_to_bottom:
                if card_id not in hand_check:
                    send_pdu(conn, {
                        "type": "ERROR",
                        "seq_num": pdu.get("seq_num", 0),
                        "code": "ILLEGAL_ACTION",
                        "message": f"Card '{card_id}' is not in hand.",
                        "rejected_action": pdu
                    })
                    return
                hand_check.remove(card_id)  # guards against listing the same card twice

            # apply: remove from hand, place on bottom of library
            for card_id in cards_to_bottom:
                player["hand"].remove(card_id)
                player["library"].insert(0, card_id)

            player["kept"] = True
            print(f"[S] {player['player_id']} kept their hand"
                  + (f", bottomed {len(cards_to_bottom)} card(s)." if cards_to_bottom else "."))

            check_mulligan_complete()

        else:
            player["mulligan_count"] += 1
            redraw_hand(player)

            server_seq_num += 1
            player["last_state_seq_num"] = server_seq_num
            send_pdu(conn, {
                "type": "GAME_STATE_UPDATE",
                "seq_num": server_seq_num,
                "state": build_personalized_mulligan_state(player)
            })
            print(f"[S] {player['player_id']} mulliganed (count={player['mulligan_count']}), redrew 7 cards.")

def handle_concede(conn, pdu):
    """Handle a CONCEDE PDU from a player (RFC 6.5 / 6.6)."""
    global game_phase
    if game_phase not in ("IN_GAME", "MULLIGAN"):
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 0),
            "code": "WRONG_PHASE",
            "message": "Cannot concede outside of an active game.",
            "rejected_action": pdu
        })
        return

    with lock:
        winner_conn = get_other_conn(conn)
        if winner_conn:
            print(f"[S] {players[conn]['player_id']} conceded.")
            trigger_game_over(winner_conn, "CONCEDE")

def handle_client(conn, addr):
    print(f"[S] Handling client {addr}")
    try:
        while True:
            pdu = recv_pdu(conn)
            if pdu is None:
                print(f"[S] Client {addr} disconnected")
                # If disconnected during an active game, remaining player wins
                handle_disconnect(conn)
                break

            msg_type = pdu.get("type")

            if msg_type == "PING":
                send_pdu(conn, {"type": "PONG", "seq_num": pdu.get("seq_num", 0), "timestamp": pdu.get("timestamp", 0)})
            elif msg_type == "PLAYER_READY":
                handle_player_ready(conn, pdu)
            elif msg_type == "MULLIGAN_CHOICE":
                handle_mulligan_choice(conn, pdu)
            elif msg_type == "PRIORITY_PASS":
                handle_priority_pass(conn, pdu)
            elif msg_type == "PLAY_LAND":
                handle_play_land(conn, pdu)
            elif msg_type == "CONCEDE":
                handle_concede(conn, pdu)
            else:
                send_pdu(conn, {
                    "type": "ERROR",
                    "seq_num": pdu.get("seq_num", 0),
                    "code": "UNKNOWN_TYPE",
                    "message": f"Unhandled type: {msg_type}"
                })
    finally:
        conn.close()
        with lock:
            if conn in connected_clients:
                connected_clients.remove(conn)
            # Only delete from players dict if in LOBBY/GAME_OVER (not waiting on a reconnect timer)
            if conn in players and game_phase not in ("IN_GAME", "MULLIGAN"):
                del players[conn]

while True:
    conn, addr = server_socket.accept()

    with lock:
        if len(connected_clients) >= 2:
            print(f"[S] Refusing extra connection from {addr}")
            conn.close()
            continue
        connected_clients.append(conn)

    print(f"[S] Accepted connection from {addr} ({len(connected_clients)}/2)")
    thread = threading.Thread(target=handle_client, args=(conn, addr))
    thread.daemon = True
    thread.start()
