import socket
import json
import struct
import threading
import random
import argparse
import datetime
import time
from protocol import MAX_PDU_SIZE, ProtocolError, encode_pdu, recv_pdu as wire_recv_pdu

HOST = "127.0.0.1"
PORT = 4444

def port_number(value):
    value=int(value)
    if not 1 <= value <= 65535: raise argparse.ArgumentTypeError("port must be 1-65535")
    return value

# --- verbose mode setup ---
# Parse --verbose / -v at startup. VERBOSE is a module-level flag that every
# send_pdu/recv_pdu call checks before printing. Toggled only via the CLI flag
# for now (RFC just requires it be toggleable at runtime via startup argument).
parser = argparse.ArgumentParser(description="MTGNP Game Server")
parser.add_argument("-v", "--verbose", action="store_true",
                     help="Print every PDU sent/received to the console")
parser.add_argument("--host", default=HOST, help="Interface to bind (default: 127.0.0.1)")
parser.add_argument("--port", type=port_number, default=PORT)
args = parser.parse_args()
VERBOSE = args.verbose
HOST, PORT = args.host, args.port

def log_pdu(direction: str, peer_label: str, pdu: dict):
    """Print a clearly-labelled, readable line for every PDU when verbose mode is on.
    direction: 'SEND' or 'RECV'
    peer_label: human-readable identifier for the other end (e.g. 'player_1' or address tuple)
    """
    if not VERBOSE:
        return
    timestamp = datetime.datetime.now().strftime("%H:%M:%S.%f")[:-3]
    label = f"S->{peer_label}" if direction == "SEND" else f"{peer_label}->S"
    print(f"[VERBOSE {timestamp}] [{label}] {json.dumps(pdu)}")

# global game_phase
game_phase = "LOBBY"
# server seq num
server_seq_num = 0

# --- turn / priority state (populated once IN_GAME begins, see begin_turn()) ---
turn_number = 0
current_step = None      # e.g. "UPKEEP", "DRAW", "PRECOMBAT_MAIN", ...
active_conn = None        # connection of the Active Player (AP) this turn
priority_conn = None       # connection that currently holds priority
priority_seq_num = None    # seq_num the priority holder must echo in PRIORITY_PASS
consecutive_passes = 0     # how many players have passed in a row in this window
stack = []                  # shared LIFO stack (empty until CAST_SPELL exists)

# Complete turn and combat sub-step order used by advance_step().
STEP_SEQUENCE = {
    "UPKEEP": "DRAW",
    "DRAW": "PRECOMBAT_MAIN",
    "PRECOMBAT_MAIN": "BEGIN_COMBAT",
    "BEGIN_COMBAT": "DECLARE_ATTACKERS",
    "DECLARE_ATTACKERS": "DECLARE_BLOCKERS",
    "DECLARE_BLOCKERS": "ASSIGN_DAMAGE_ORDER",
    "ASSIGN_DAMAGE_ORDER": "COMBAT_DAMAGE",
    "FIRST_STRIKE_DAMAGE": "COMBAT_DAMAGE",
    "COMBAT_DAMAGE": "END_OF_COMBAT",
    "END_OF_COMBAT": "POSTCOMBAT_MAIN",
    "POSTCOMBAT_MAIN": "END_STEP",
    "END_STEP": "CLEANUP",
}
# Steps that open a priority window (all of Section 7's steps except UNTAP
# and CLEANUP, which never grant priority per the RFC).
PRIORITY_STEPS = {"UPKEEP", "DRAW", "PRECOMBAT_MAIN", "BEGIN_COMBAT", "END_OF_COMBAT", "POSTCOMBAT_MAIN", "END_STEP"}

server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
server_socket.bind((HOST, PORT))
server_socket.listen(5)
print(f"[S] Listening on {HOST}:{PORT}")

# load card catalog — keyed by individual card INSTANCE id (e.g. "mountain_001"),
# not base card name. Generated by build_catalog.py from mtgnp_master_card_list.xlsx.
# This is the shared out-of-band catalog referenced in RFC Section 1.
with open("card_instances.json", "r") as f:
    cards = json.load(f)

connected_clients = []       
players = {}                 
lock = threading.RLock()  # callbacks may safely invoke other state-changing helpers
stack_counter = 0
attackers = []
blockers = {}
damage_orders = {}
trigger_counter = 0
pending_trigger_orders = {}
pending_trigger_choices = {}
trigger_resume_conn = None
combat_request_seq = None

def get_peer_label(sock):
    """Prefer the player_id if this connection has registered one; fall back to address."""
    info = players.get(sock)
    if info and info.get("player_id"):
        return info["player_id"]
    try:
        addr = sock.getpeername()
        return f"{addr[0]}:{addr[1]}"
    except OSError:
        return "unknown"

def send_pdu(sock, pdu: dict): #to send a PDU to the socket
    if not isinstance(pdu, dict) or "type" not in pdu or "seq_num" not in pdu:
        raise ValueError("Every PDU must contain type and seq_num")
    log_pdu("SEND", get_peer_label(sock), pdu)
    sock.sendall(encode_pdu(pdu))

def recv_exact(sock, n): #to recv exact n bytes from socket
    data = b""
    while len(data) < n:
        chunk = sock.recv(n - len(data))
        if not chunk:
            return None
        data += chunk
    return data

def recv_pdu(sock):
    pdu = wire_recv_pdu(sock)
    if pdu is None: return None
    log_pdu("RECV", get_peer_label(sock), pdu)
    return pdu

def broadcast_lobby_status():
    global server_seq_num
    """Send every ready player an updated GAME_STATE_UPDATE (lobby variant)."""
    with lock:
        ready_ids = [p["player_id"] for p in players.values()]
        snapshot_conns = list(players.keys())
    all_ids = ["player_1", "player_2"]
    waiting_for = [pid for pid in all_ids if pid not in ready_ids]

    for conn in snapshot_conns:
        server_seq_num += 1

        send_pdu(conn, {
            "type": "GAME_STATE_UPDATE",
            "seq_num": server_seq_num,
            "state": {
                "phase": "LOBBY",
                "players_ready": len(players),
                "waiting_for": waiting_for
            }
        })

def handle_player_ready(conn, pdu):
    global game_phase, active_conn, priority_conn

    # A disconnected player reclaims the same authoritative state by presenting
    # the same ID and deck before the grace timer expires.
    requested_id = pdu.get("player_id")
    with lock:
        old_conn = next((c for c, info in players.items()
                         if info.get("player_id") == requested_id and not info.get("connected", True)), None)
        if old_conn is not None and game_phase in ("MULLIGAN", "IN_GAME"):
            info = players.pop(old_conn)
            if pdu.get("deck_list") != info.get("deck_list"):
                players[old_conn] = info
                send_pdu(conn, {"type": "ERROR", "seq_num": pdu.get("seq_num", 0), "code": "ILLEGAL_DECK", "message": "Reconnect deck does not match."})
                return
            if info.get("reconnect_timer"): info["reconnect_timer"].cancel()
            info.update({"connected": True, "reconnect_timer": None})
            players[conn] = info
            if active_conn is old_conn: active_conn = conn
            if priority_conn is old_conn: priority_conn = conn
            send_pdu(conn, {"type": "GAME_STATE_UPDATE", "seq_num": next_server_seq(),
                            "state": build_personalized_mulligan_state(info) if game_phase == "MULLIGAN" else build_ingame_state(info)})
            if priority_conn is conn: grant_priority(conn)
            print(f"[S] {requested_id} reconnected")
            return

    if game_phase != "LOBBY":
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 1),
            "code": "INVALID_STATE",
            "message": "PLAYER_READY is only allowed while in the LOBBY."
        })
        return
    
    player_id = pdu.get("player_id")
    deck_list = pdu.get("deck_list")

    # Validate deck list format
    if not string_id(player_id):
        send_pdu(conn, {"type": "ERROR", "seq_num": pdu.get("seq_num", 0),
                        "code": "ILLEGAL_ACTION", "message": "player_id must be non-empty."})
        return
    if not string_list(deck_list,True) or len(deck_list) < 1 or len(deck_list) > 50:
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 1),
            "code": "ILLEGAL_DECK",
            "message": f"Deck contains {len(deck_list) if isinstance(deck_list, list) else 0} cards; must be 1-50."
        })
        return

    # Validate card IDs
    illegal_cards = [card_id for card_id in deck_list if card_id not in cards]
    if illegal_cards:
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 1),
            "code": "ILLEGAL_DECK",
            "message": f"Unknown card IDs: {', '.join(illegal_cards)}"
        })
        return

    # Validate duplicates
    if len(deck_list) != len(set(deck_list)):
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 1),
            "code": "ILLEGAL_DECK",
            "message": "Duplicate card instance(s) in deck."
        })
        return

    should_start_setup = False
    with lock:
        # Check duplicate ID across existing connections
        for other_conn, other_info in players.items():
            if other_conn != conn and other_info["player_id"] == player_id:
                send_pdu(conn, {
                    "type": "ERROR",
                    "seq_num": pdu.get("seq_num", 1),
                    "code": "DUPLICATE_ID",
                    "message": f"player_id '{player_id}' is already taken."
                })
                return

        # Add or update player outside of the loop
        if conn in players:
            players[conn]["player_id"] = player_id
            players[conn]["deck_list"] = deck_list
            print(f"[S] {player_id} updated their deck ({len(deck_list)} cards)")
        else:
            players[conn] = {
                "player_id": player_id,
                "deck_list": deck_list,
                "library": [],
                "hand": [],
                "life": 20,
                "mulligan_count": 0,
                "kept": False,
                "last_state_seq_num": None,
                "battlefield": [],
                "graveyard": [],
                "land_played_this_turn": False,
                "mana_pool": {c: 0 for c in "WUBRGC"},
                "connected": True,
                "reconnect_timer": None
            }
            print(f"[S] {player_id} is ready with {len(deck_list)} cards ({len(players)}/2)")

        if len(players) == 2 and game_phase == "LOBBY":
            game_phase = "GAME_SETUP"
            should_start_setup = True

    broadcast_lobby_status()

    if should_start_setup:
        print("[S] Both players ready — transitioning to GAME_SETUP")
        start_game_setup()

def get_starting_player_id():
    """Look up which player was chosen to go first (set once in start_game_setup)."""
    for info in players.values():
        if info.get("is_starting_player"):
            return info["player_id"]
    return None

def get_starting_conn():
    """Same as get_starting_player_id but returns the connection object."""
    for conn, info in players.items():
        if info.get("is_starting_player"):
            return conn
    return None

def get_other_conn(conn):
    """Given one player's connection, return the opponent's connection."""
    for c in players:
        if c != conn:
            return c
    return None

def build_personalized_mulligan_state(player):
    """Build the MULLIGAN-phase state object personalized for one player.
    Used both for the initial post-setup broadcast and for post-redraw updates."""
    return {
        "turn": 0,
        "phase": "MULLIGAN",
        "active_player": get_starting_player_id(),
        "life_totals": {
            info["player_id"]: info["life"]
            for info in players.values()
        },
        "hand": player["hand"],
        "hand_counts": {
            info["player_id"]: len(info["hand"])
            for info in players.values()
            if info is not player
        },
        "library_counts": {
            info["player_id"]: len(info["library"])
            for info in players.values()
        },
        "battlefield": {
            info["player_id"]: info["battlefield"]
            for info in players.values()
        },
        "graveyard": {
            info["player_id"]: info["graveyard"]
            for info in players.values()
        },
        "stack": []
    }

def build_ingame_state(player):
    """Build the IN_GAME-phase state object personalized for one player
    (RFC Section 10.2.2, in-game variant)."""
    return {
        "turn": turn_number,
        "phase": "IN_GAME",
        "step": current_step,
        "active_player": players[active_conn]["player_id"],
        "priority_holder": players[priority_conn]["player_id"] if priority_conn else None,
        "life_totals": {
            info["player_id"]: info["life"]
            for info in players.values()
        },
        "stack": [{"stack_item_id": x["stack_item_id"], "item_type": x["item_type"],
                   "source": x["source_id"], "controller": x["controller_id"], "targets": x["targets"]} for x in stack],
        "battlefield": {
            info["player_id"]: info["battlefield"]
            for info in players.values()
        },
        "graveyard": {
            info["player_id"]: info["graveyard"]
            for info in players.values()
        },
        "hand": player["hand"],
        "hand_counts": {
            info["player_id"]: len(info["hand"])
            for info in players.values()
            if info is not player
        },
        "library_counts": {
            info["player_id"]: len(info["library"])
            for info in players.values()
        },
        "land_played_this_turn": player["land_played_this_turn"]
    }

def broadcast_ingame_state():
    """Send every player a personalized IN_GAME GAME_STATE_UPDATE."""
    global server_seq_num

    # check for state-based win/loss conditions
    if check_life_totals():
        return #trigger_game_over() is called
    
    for conn, player in list(players.items()):
        server_seq_num += 1
        send_pdu(conn, {
            "type": "GAME_STATE_UPDATE",
            "seq_num": server_seq_num,
            "state": build_ingame_state(player)
        })

def start_game_setup():
    global game_phase
    global server_seq_num

    print("[S] Starting GAME_SETUP")

    with lock:
        #initialize player life to 20
        for player in players.values():
            player["life"] = 20

        # shuffle deck
        for player in players.values():
            player["library"] = player["deck_list"][:]
            random.shuffle(player["library"])

        # draw seven cards
        for player in players.values():
            player["hand"] = []

            while player["library"] and len(player["hand"]) < 7:
                player["hand"].append(player["library"].pop())

        # choose player to start
        starting_conn = random.choice(list(players.keys()))

        for conn, player in players.items():
            player["is_starting_player"] = (conn == starting_conn)

        # Flip to MULLIGAN before sending, since a fast client could otherwise reply
        # before the server considers itself out of GAME_SETUP.
        game_phase = "MULLIGAN"

        # send personalized game state update to each player
        for conn, player in players.items():
            server_seq_num += 1
            player["last_state_seq_num"] = server_seq_num

            send_pdu(conn, {
                "type": "GAME_STATE_UPDATE",
                "seq_num": server_seq_num,
                "state": build_personalized_mulligan_state(player)
            })

    print("[S] Transitioned to MULLIGAN")

def redraw_hand(player):
    """London Mulligan redraw: shuffle hand back into library, reshuffle, draw a fresh 7."""
    player["library"].extend(player["hand"])
    player["hand"] = []
    random.shuffle(player["library"])
    while player["library"] and len(player["hand"]) < 7:
        player["hand"].append(player["library"].pop())

def check_mulligan_complete():
    """If both players have kept, transition to IN_GAME and start Turn 1's Untap Step.
    Caller must hold `lock`."""
    global game_phase

    if len(players) != 2 or not all(info.get("kept") for info in players.values()):
        return

    game_phase = "IN_GAME"
    print("[S] Both players kept — transitioning to IN_GAME (Turn 1, UNTAP)")
    begin_turn(get_starting_conn(), 1, from_phase="MULLIGAN")

def begin_turn(conn, turn_num, from_phase):
    """Starts a new turn for `conn` as the Active Player.
    Performs the Untap Step (RFC 7.2) — untap AP's permanents, reset the
    land-per-turn flag — then auto-advances into Upkeep (Untap never opens
    a priority window)."""
    global active_conn, turn_number, current_step, server_seq_num

    active_conn = conn
    turn_number = turn_num
    current_step = "UNTAP"

    player = players[active_conn]

    # Untap every permanent controlled by the active player.
    for permanent in player["battlefield"]:
        permanent["tapped"] = False
    player["land_played_this_turn"] = False
    player["mana_pool"] = {c: 0 for c in "WUBRGC"}

    server_seq_num += 1
    for c in list(players.keys()):
        send_pdu(c, {
            "type": "PHASE_TRANSITION",
            "seq_num": server_seq_num,
            "from_phase": from_phase,
            "to_phase": "UNTAP",
            "active_player": player["player_id"],
            "turn": turn_num
        })

    # broadcast the untaapped state to both players (RFC 7.2)
    broadcast_ingame_state()

    print(f"[S] Turn {turn_num} — {player['player_id']} untaps")

    # UNTAP never opens a priority window — go straight to UPKEEP.
    current_step = "UPKEEP"
    server_seq_num += 1
    for c in list(players.keys()):
        send_pdu(c, {
            "type": "PHASE_TRANSITION",
            "seq_num": server_seq_num,
            "from_phase": "UNTAP",
            "to_phase": "UPKEEP",
            "active_player": player["player_id"],
            "turn": turn_num
        })
    enter_step("UPKEEP")

def enter_step(step_name):
    """Perform any automatic server-side actions for entering a step, then
    open a priority window if this step grants one (RFC Section 7)."""
    global current_step
    current_step = step_name

    if step_name == "DRAW":
        do_draw_step()
        if game_phase != "IN_GAME":
            return  # do_draw_step() may have ended the game (empty-library loss)

    if step_name == "CLEANUP":
        do_cleanup_step()
        return

    if step_name == "DECLARE_ATTACKERS":
        return
    if step_name == "DECLARE_BLOCKERS":
        return
    if step_name == "ASSIGN_DAMAGE_ORDER":
        if any(len(v) > 1 for v in blockers.values()): return
        else: begin_combat_damage()
        return
    if step_name == "COMBAT_DAMAGE":
        resolve_combat_damage(first_strike=False)
        return

    if step_name in PRIORITY_STEPS:
        open_priority_window()

def do_draw_step():
    """RFC 7.4: AP draws one card, except the first player's very first turn."""
    player = players[active_conn]
    skip_draw = (turn_number == 1 and player.get("is_starting_player"))

    if not skip_draw:
        if not player["library"]:
            # RFC 6.5: being required to draw from an empty library is a loss.
            trigger_game_over(get_other_conn(active_conn), "DECK_EMPTY")
            return
        player["hand"].append(player["library"].pop())

    broadcast_ingame_state()

def open_priority_window():
    """Opens a priority window for the current step, giving the Active
    Player priority first (RFC Section 8.1, rule 1)."""
    global consecutive_passes
    consecutive_passes = 0
    grant_priority(active_conn)

def grant_priority(conn):
    """Send PRIORITY_GRANT to `conn` and record the seq_num it must echo
    when it responds (PRIORITY_PASS, CAST_SPELL, etc. — RFC Section 5.4/8.5)."""
    global priority_conn, priority_seq_num, server_seq_num
    priority_conn = conn
    server_seq_num += 1
    priority_seq_num = server_seq_num
    send_pdu(conn, {
        "type": "PRIORITY_GRANT",
        "player_id": players[conn]["player_id"],
        "seq_num": server_seq_num,
        "time_limit_ms": 60000
    })

def advance_step():
    """Called when both players have passed priority consecutively with an
    empty stack (RFC Section 8.1, rule 6). Moves to the next step per the
    Section 7 turn structure, or starts the next player's turn at CLEANUP."""
    global server_seq_num, combat_request_seq

    next_step = STEP_SEQUENCE.get(current_step)
    if next_step is None:
        return  # only CLEANUP has no "next" here; handled by do_cleanup_step

    old_step = current_step
    server_seq_num += 1
    if next_step in ("DECLARE_ATTACKERS", "DECLARE_BLOCKERS", "ASSIGN_DAMAGE_ORDER"):
        combat_request_seq = server_seq_num
    for conn in list(players.keys()):
        send_pdu(conn, {
            "type": "PHASE_TRANSITION",
            "seq_num": server_seq_num,
            "from_phase": old_step,
            "to_phase": next_step,
            "active_player": players[active_conn]["player_id"],
            "turn": turn_number
        })

    enter_step(next_step)

def do_cleanup_step():
    """RFC 7.8: Remove damage, clear until-end-of-turn effects, enforce maximum
    hand size (7 cards), and start the next player's turn."""
    active_player = players[active_conn]
    print(f"[S] Cleanup — turn {turn_number} ends for {active_player['player_id']}")

    # Check maximum hand size requirement (RFC 7.8)
    if len(active_player["hand"]) > 7:
        print(f"[S] {active_player['player_id']} has {len(active_player['hand'])} cards; awaiting DISCARD PDU(s)...")
        # Send an updated state to the AP so they have the seq_num to echo in DISCARD
        global server_seq_num
        server_seq_num += 1
        active_player["last_state_seq_num"] = server_seq_num
        send_pdu(active_conn, {
            "type": "GAME_STATE_UPDATE",
            "seq_num": server_seq_num,
            "state": build_ingame_state(active_player)
        })
        return  # Pause and wait for handle_discard

    finish_cleanup_step()

def finish_cleanup_step():
    """Clear end-of-turn state and advance to the next player's Untap Step."""
    # Remove all damage from creatures and clear "until end of turn" effects
    for player in players.values():
        for permanent in player["battlefield"]:
            permanent["damage"] = 0
            permanent.pop("power_bonus", None)
            permanent.pop("toughness_bonus", None)
            # clear "until end of turn" temporary modifiers here when implemented

    # Broadcast updated game state reflecting the cleared state
    broadcast_ingame_state()

    # Increment turn counter, switch Active Player, and begin Untap Step
    next_conn = get_other_conn(active_conn)
    begin_turn(next_conn, turn_number + 1, from_phase="CLEANUP")

def check_life_totals():
    """Checks if any player's life total has reached <= 0 (RFC 6.5)."""
    if game_phase != "IN_GAME":
        return False

    dead_players = [conn for conn, info in players.items() if info["life"] <= 0]
    if dead_players:
        # If one player drops <= 0, the other wins
        for conn in list(players.keys()):
            if conn not in dead_players:
                trigger_game_over(conn, "LIFE_ZERO")
                return True
    return False

def trigger_game_over(winner_conn, reason):
    """Broadcast GAME_OVER and return to LOBBY (RFC Section 6.6)."""
    global game_phase, server_seq_num, turn_number, current_step, priority_conn, active_conn, attackers, blockers, damage_orders
    winner_id = players[winner_conn]["player_id"]
    loser_conn = get_other_conn(winner_conn)
    loser_id = players[loser_conn]["player_id"] if loser_conn else None

    # cancel any running reconnect timers
    for info in players.values():
        if info.get("reconnect_timer"):
            info["reconnect_timer"].cancel()
            info["reconnect_timer"] = None

    for conn in list(players.keys()):
        if players[conn].get("connected", True):
            server_seq_num += 1
            send_pdu(conn, {
                "type": "GAME_OVER",
                "seq_num": server_seq_num,
                "winner_id": winner_id,
                "loser_id": loser_id,
                "reason": reason
            })

    print(f"[S] GAME_OVER — {winner_id} wins ({reason})")

    # reset internal game state variables
    game_phase = "LOBBY"
    turn_number = 0
    current_step = None
    stack.clear()
    pending_trigger_orders.clear(); pending_trigger_choices.clear()
    attackers = []; blockers = {}; damage_orders = {}
    priority_conn = None; active_conn = None

    # reset player-specific game state for remaining connections
    for player_info in players.values():
        player_info["library"] = []
        player_info["hand"] = []
        player_info["battlefield"] = []
        player_info["graveyard"] = []
        player_info["life"] = 20
        player_info["mulligan_count"] = 0
        player_info["kept"] = False
        player_info["is_starting_player"] = False
        player_info["land_played_this_turn"] = False
        player_info["mana_pool"] = {c: 0 for c in "WUBRGC"}

    # Notify remaining clients of returning to LOBBY
    broadcast_lobby_status()
    

def handle_priority_pass(conn, pdu):
    """Handle a PRIORITY_PASS PDU (RFC Section 8.2)."""
    global consecutive_passes

    if game_phase != "IN_GAME":
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 0),
            "code": "WRONG_PHASE",
            "message": "PRIORITY_PASS is only valid during IN_GAME.",
            "rejected_action": pdu
        })
        return

    with lock:
        if conn != priority_conn:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "NOT_YOUR_PRIORITY",
                "message": "You do not currently hold priority.",
                "rejected_action": pdu
            })
            return

        if pdu.get("seq_num") != priority_seq_num:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "STALE_ACTION",
                "message": f"Priority token mismatch. Expected seq_num {priority_seq_num}, got {pdu.get('seq_num')}.",
                "rejected_action": pdu
            })
            return

        consecutive_passes += 1
        print(f"[S] {players[conn]['player_id']} passes priority ({consecutive_passes}/2)")

        if consecutive_passes >= 2:
            if stack:
                resolve_stack_top()
            else:
                advance_step()
        else:
            grant_priority(get_other_conn(conn))

def handle_play_land(conn, pdu):
    """Handle a PLAY_LAND PDU (RFC Section 7.5 / 10.2.19).
    Sorcery-speed, Active-Player-only, one per turn, doesn't touch the stack.
    The Active Player retains priority afterward (a fresh PRIORITY_GRANT)."""
    if game_phase != "IN_GAME":
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 0),
            "code": "WRONG_PHASE",
            "message": "PLAY_LAND is only valid during IN_GAME.",
            "rejected_action": pdu
        })
        return

    if current_step not in ("PRECOMBAT_MAIN", "POSTCOMBAT_MAIN"):
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 0),
            "code": "WRONG_PHASE",
            "message": "Lands may only be played during a Main Phase.",
            "rejected_action": pdu
        })
        return

    with lock:
        # PLAY_LAND is a priority-bearing PDU (RFC 5.4) — same seq_num/holder
        # rules as PRIORITY_PASS apply.
        if conn != priority_conn:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "NOT_YOUR_PRIORITY",
                "message": "You do not currently hold priority.",
                "rejected_action": pdu
            })
            return

        if pdu.get("seq_num") != priority_seq_num:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "STALE_ACTION",
                "message": f"Priority token mismatch. Expected seq_num {priority_seq_num}, got {pdu.get('seq_num')}.",
                "rejected_action": pdu
            })
            return

        if conn != active_conn:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "ILLEGAL_ACTION",
                "message": "Only the Active Player may play a land.",
                "rejected_action": pdu
            })
            return

        player = players[conn]

        if player["land_played_this_turn"]:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "ILLEGAL_ACTION",
                "message": "You have already played a land this turn.",
                "rejected_action": pdu
            })
            return

        card_id = pdu.get("card_id")

        if card_id not in player["hand"]:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "ILLEGAL_ACTION",
                "message": f"Card '{card_id}' is not in your hand.",
                "rejected_action": pdu
            })
            return

        card_info = cards.get(card_id)
        if card_info is None or card_info.get("card_type") != "Land":
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "ILLEGAL_ACTION",
                "message": f"Card '{card_id}' is not a Land.",
                "rejected_action": pdu
            })
            return

        # Apply: move from hand to battlefield as an untapped permanent.
        player["hand"].remove(card_id)
        player["battlefield"].append({"id": card_id, "tapped": False})
        player["land_played_this_turn"] = True

        print(f"[S] {player['player_id']} plays land {card_id}")

        broadcast_ingame_state()
        # AP retains priority — issue a fresh PRIORITY_GRANT (RFC 7.5).
        open_priority_window()

RECONNECT_TIMEOUT_SEC = 30.0  # Adjust implementation-defined timeout as needed

def handle_reconnect_timeout(player_id):
    """Callback when reconnect timer expires."""
    with lock:
        if game_phase not in ("IN_GAME", "MULLIGAN"):
            return

        # Find the player who timed out
        offending_conn = None
        for conn, info in players.items():
            if info["player_id"] == player_id and not info["connected"]:
                offending_conn = conn
                break

        if offending_conn:
            print(f"[S] Reconnect timer expired for {player_id}.")
            winner_conn = get_other_conn(offending_conn)
            if winner_conn:
                trigger_game_over(winner_conn, "DISCONNECT")


def handle_disconnect(conn):
    """Handle lost connection with a grace period timer."""
    global game_phase
    with lock:
        if conn not in players:
            return

        player_info = players[conn]
        player_info["connected"] = False
        pid = player_info["player_id"]

        if game_phase in ("IN_GAME", "MULLIGAN"):
            print(f"[S] {pid} disconnected. Starting {RECONNECT_TIMEOUT_SEC}s reconnect timer...")
            
            # Start timer thread to wait for reconnection
            timer = threading.Timer(RECONNECT_TIMEOUT_SEC, handle_reconnect_timeout, args=[pid])
            player_info["reconnect_timer"] = timer
            timer.start()
        else:
            # In LOBBY or GAME_OVER, remove connection immediately
            del players[conn]

def handle_mulligan_choice(conn, pdu):
    """Handle a MULLIGAN_CHOICE PDU per RFC Section 6.4."""
    global server_seq_num

    if game_phase != "MULLIGAN":
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 0),
            "code": "WRONG_PHASE",
            "message": "MULLIGAN_CHOICE is only allowed during the MULLIGAN phase.",
            "rejected_action": pdu
        })
        return

    with lock:
        player = players.get(conn)
        if player is None:
            return

        # seq_num must echo the most recently sent GAME_STATE_UPDATE for this player
        expected_seq = player.get("last_state_seq_num")
        if pdu.get("seq_num") != expected_seq:
            send_pdu(conn, {
                "type": "ERROR",
                "seq_num": pdu.get("seq_num", 0),
                "code": "STALE_ACTION",
                "message": f"Priority token mismatch. Expected seq_num {expected_seq}, got {pdu.get('seq_num')}.",
                "rejected_action": pdu
            })
            return

        keep = pdu.get("keep")
        cards_to_bottom = pdu.get("cards_to_bottom", [])
        if not isinstance(keep,bool) or not string_list(cards_to_bottom,True):
            error(conn,pdu,"ILLEGAL_ACTION","keep must be boolean and cards_to_bottom must be a unique card-ID list."); return
        if not keep and cards_to_bottom:
            error(conn,pdu,"ILLEGAL_ACTION","cards_to_bottom must be empty when mulliganing."); return

        if keep:
            mulligan_count = player["mulligan_count"]

            # cards_to_bottom must contain exactly N card IDs, all currently in hand
            if not isinstance(cards_to_bottom, list) or len(cards_to_bottom) != mulligan_count:
                send_pdu(conn, {
                    "type": "ERROR",
                    "seq_num": pdu.get("seq_num", 0),
                    "code": "ILLEGAL_ACTION",
                    "message": f"cards_to_bottom must contain exactly {mulligan_count} card ID(s); got {len(cards_to_bottom) if isinstance(cards_to_bottom, list) else 'invalid'}.",
                    "rejected_action": pdu
                })
                return

            hand_check = list(player["hand"])
            for card_id in cards_to_bottom:
                if card_id not in hand_check:
                    send_pdu(conn, {
                        "type": "ERROR",
                        "seq_num": pdu.get("seq_num", 0),
                        "code": "ILLEGAL_ACTION",
                        "message": f"Card '{card_id}' is not in hand.",
                        "rejected_action": pdu
                    })
                    return
                hand_check.remove(card_id)  # guards against listing the same card twice

            # apply: remove from hand, place on bottom of library
            for card_id in cards_to_bottom:
                player["hand"].remove(card_id)
                player["library"].insert(0, card_id)

            player["kept"] = True
            print(f"[S] {player['player_id']} kept their hand"
                  + (f", bottomed {len(cards_to_bottom)} card(s)." if cards_to_bottom else "."))

            check_mulligan_complete()

        else:
            player["mulligan_count"] += 1
            redraw_hand(player)

            server_seq_num += 1
            player["last_state_seq_num"] = server_seq_num
            send_pdu(conn, {
                "type": "GAME_STATE_UPDATE",
                "seq_num": server_seq_num,
                "state": build_personalized_mulligan_state(player)
            })
            print(f"[S] {player['player_id']} mulliganed (count={player['mulligan_count']}), redrew 7 cards.")

def handle_concede(conn, pdu):
    """Handle a CONCEDE PDU from a player (RFC 6.5 / 6.6)."""
    global game_phase
    if game_phase not in ("IN_GAME", "MULLIGAN"):
        send_pdu(conn, {
            "type": "ERROR",
            "seq_num": pdu.get("seq_num", 0),
            "code": "WRONG_PHASE",
            "message": "Cannot concede outside of an active game.",
            "rejected_action": pdu
        })
        return

    with lock:
        winner_conn = get_other_conn(conn)
        if winner_conn:
            print(f"[S] {players[conn]['player_id']} conceded.")
            trigger_game_over(winner_conn, "CONCEDE")

def error(conn, pdu, code, message):
    send_pdu(conn, {"type": "ERROR", "seq_num": pdu.get("seq_num", 0),
                    "code": code, "message": message, "rejected_action": pdu})

def string_id(value):
    return isinstance(value,str) and 0 < len(value.strip()) <= 128 and not any(ord(ch)<32 for ch in value)

def string_list(value, unique=False):
    return isinstance(value,list) and all(string_id(x) for x in value) and (not unique or len(value)==len(set(value)))

def require_fields(conn,pdu,checks):
    """checks maps field names to predicates; malformed fields never reach game logic."""
    bad=[name for name,predicate in checks.items() if not predicate(pdu.get(name))]
    if bad:
        error(conn,pdu,"ILLEGAL_ACTION","Malformed or missing field(s): "+", ".join(bad))
        return False
    return True

def validate_priority(conn, pdu):
    if game_phase != "IN_GAME":
        error(conn, pdu, "WRONG_PHASE", "Action is only valid during IN_GAME.")
        return False
    if conn != priority_conn:
        error(conn, pdu, "NOT_YOUR_PRIORITY", "You do not hold priority.")
        return False
    if pdu.get("seq_num") != priority_seq_num:
        error(conn, pdu, "STALE_ACTION", f"Expected seq_num {priority_seq_num}.")
        return False
    return True

def broadcast(pdu):
    for c, info in list(players.items()):
        if info.get("connected", True):
            send_pdu(c, dict(pdu))

def mana_available(player):
    pool = {c: 0 for c in "WUBRG"}
    lands = []
    subtype_color = {"Plains": "W", "Island": "U", "Swamp": "B", "Mountain": "R", "Forest": "G"}
    for perm in player["battlefield"]:
        info = cards.get(perm["id"], {})
        if info.get("card_type") == "Land" and not perm.get("tapped"):
            color = next((v for k, v in subtype_color.items() if k in str(info.get("subtype"))), info.get("color"))
            if color in pool:
                pool[color] += 1
                lands.append((perm, color))
    return pool, lands

def pay_mana(player, card):
    pool, lands = mana_available(player)
    cost = {k: int(v or 0) for k, v in card.get("cost", {}).items()}
    mana_pool = player.setdefault("mana_pool", {c: 0 for c in "WUBRGC"})
    for color in "WUBRG":
        use = min(mana_pool.get(color, 0), cost.get(color, 0)); mana_pool[color] -= use; cost[color] -= use
        if pool[color] < cost.get(color, 0):
            return False
        pool[color] -= cost.get(color, 0)
    if sum(pool.values()) < cost.get("Generic", 0):
        return False
    needed = {c: cost.get(c, 0) for c in "WUBRG"}
    generic = cost.get("Generic", 0)
    for perm, color in lands:
        if needed[color] > 0:
            perm["tapped"] = True; needed[color] -= 1
        elif generic > 0:
            perm["tapped"] = True; generic -= 1
    return True

def pay_generic(player, amount):
    pool = player.setdefault("mana_pool", {c: 0 for c in "WUBRGC"})
    for color in "WUBRGC":
        used = min(pool.get(color, 0), amount); pool[color] -= used; amount -= used
    if amount == 0: return True
    _, lands = mana_available(player)
    if len(lands) < amount: return False
    for perm, _ in lands[:amount]: perm["tapped"] = True
    return True

def legal_target(target):
    if target in [p["player_id"] for p in players.values()]:
        return True
    return any(target == perm.get("id") for p in players.values() for perm in p["battlefield"])

def handle_cast_spell(conn, pdu):
    global stack_counter, consecutive_passes, trigger_resume_conn
    with lock:
        if not validate_priority(conn, pdu): return
        if not require_fields(conn,pdu,{"card_id":string_id,"targets":lambda x:string_list(x,True),
                                        "mana_payment":lambda x:isinstance(x,dict) and all(k in "WUBRGX" and isinstance(v,int) and not isinstance(v,bool) and v>=0 for k,v in x.items())}): return
        card_id = pdu.get("card_id")
        if not string_id(card_id):
            error(conn,pdu,"ILLEGAL_ACTION","card_id must be a non-empty string."); return
        if not string_id(card_id):
            error(conn,pdu,"ILLEGAL_ACTION","card_id must be a non-empty string."); return
        player = players[conn]
        card = cards.get(card_id)
        if card_id not in player["hand"] or not card or card.get("card_type") == "Land":
            error(conn, pdu, "ILLEGAL_ACTION", "Spell card is not in your hand."); return
        if card.get("card_type") in ("Creature", "Sorcery") and (conn != active_conn or current_step not in ("PRECOMBAT_MAIN", "POSTCOMBAT_MAIN") or stack):
            error(conn, pdu, "WRONG_PHASE", "Sorcery-speed spell cannot be cast now."); return
        targets = pdu.get("targets", [])
        if not isinstance(targets, list) or any(not legal_target(t) for t in targets):
            error(conn, pdu, "ILLEGAL_TARGET", "One or more targets are illegal."); return
        if not pay_mana(player, card):
            error(conn, pdu, "INSUFFICIENT_MANA", "Not enough untapped lands."); return
        player["hand"].remove(card_id)
        stack_counter += 1
        item = {"stack_item_id": f"stk_{stack_counter:04d}", "item_type": "SPELL",
                "source_id": card_id, "controller_id": player["player_id"], "targets": targets}
        stack.append(item); consecutive_passes = 0
        next_seq = next_server_seq()
        broadcast({"type": "STACK_PUSH", "seq_num": next_seq, "stack_item_id": item["stack_item_id"],
                   "item_type": item["item_type"], "source": item["source_id"],
                   "controller": item["controller_id"], "targets": item["targets"]})
        broadcast_ingame_state()
        fired = []
        if card.get("card_type") != "Creature":
            for perm in player["battlefield"]:
                if cards.get(perm["id"], {}).get("card_name") == "Monastery Swiftspear":
                    fired.append(make_trigger(conn, perm["id"], "PROWESS"))
        # Being targeted triggers Phantasmal Bear.
        for target_id in targets:
            owner, perm = find_permanent(target_id)
            if perm and cards.get(target_id,{}).get("card_name") == "Phantasmal Bear":
                fired.append(make_trigger(owner, target_id, "SACRIFICE_SELF"))
        trigger_resume_conn = conn
        queue_triggers(fired)
        if not pending_trigger_orders and not pending_trigger_choices: grant_priority(conn)

def handle_activate_ability(conn, pdu):
    global stack_counter, consecutive_passes
    with lock:
        if not validate_priority(conn, pdu): return
        if not require_fields(conn,pdu,{"source_id":string_id,"ability_index":lambda x:isinstance(x,int) and not isinstance(x,bool) and x>=0,
                                        "targets":lambda x:string_list(x,True),"cost_payment":lambda x:isinstance(x,dict)}): return
        source = pdu.get("source_id"); player = players[conn]
        perm = next((x for x in player["battlefield"] if x.get("id") == source), None)
        card = cards.get(source, {}); name = card.get("card_name")
        if not perm or pdu.get("ability_index") != 0:
            error(conn, pdu, "ILLEGAL_ACTION", "Unknown permanent or ability index."); return
        supported = {"Llanowar Elves", "Elvish Mystic", "Sol Ring", "Merfolk Looter", "Prodigal Sorcerer", "Royal Assassin", "Millstone", "Rod of Ruin"}
        if name not in supported or perm.get("tapped"):
            error(conn, pdu, "ILLEGAL_ACTION", "Ability is unsupported or its source is tapped."); return
        targets = pdu.get("targets", [])
        if any(not legal_target(t) for t in targets): error(conn, pdu, "ILLEGAL_TARGET", "Illegal ability target."); return
        generic_cost = {"Millstone":2, "Rod of Ruin":3}.get(name, 0)
        if generic_cost and not pay_generic(player, generic_cost): error(conn, pdu, "INSUFFICIENT_MANA", "Cannot pay activation cost."); return
        perm["tapped"] = True
        if name in ("Llanowar Elves", "Elvish Mystic", "Sol Ring"):
            color, amount = ("G", 1) if name != "Sol Ring" else ("C", 2)
            player["mana_pool"][color] += amount
            broadcast_ingame_state(); grant_priority(conn); return
        stack_counter += 1
        item = {"stack_item_id": f"stk_{stack_counter:04d}", "item_type":"ABILITY", "source_id":source,
                "controller_id":player["player_id"], "targets":targets, "ability_index":0}
        stack.append(item); consecutive_passes = 0
        broadcast({"type":"STACK_PUSH","seq_num":next_server_seq(),"stack_item_id":item["stack_item_id"],
                   "item_type":"ABILITY","source":source,"controller":player["player_id"],"targets":targets})
        grant_priority(conn)

def next_server_seq():
    global server_seq_num
    server_seq_num += 1
    return server_seq_num

def make_trigger(controller_conn, source_id, effect, targets=None):
    global trigger_counter
    trigger_counter += 1
    return {"trigger_id":f"trg_{trigger_counter:04d}", "controller_conn":controller_conn,
            "source_id":source_id, "effect":effect, "targets":targets or []}

def push_trigger(trigger):
    global stack_counter
    stack_counter += 1
    item={"stack_item_id":f"stk_{stack_counter:04d}","item_type":"TRIGGER_ABILITY",
          "source_id":trigger["source_id"],"controller_id":players[trigger["controller_conn"]]["player_id"],
          "targets":trigger.get("targets",[]),"trigger_effect":trigger["effect"]}
    stack.append(item)
    broadcast({"type":"STACK_PUSH","seq_num":next_server_seq(),"stack_item_id":item["stack_item_id"],
               "item_type":"TRIGGER_ABILITY","source":item["source_id"],"controller":item["controller_id"],"targets":item["targets"]})

def queue_triggers(fired):
    """Return True when triggers were pushed or a mandatory decision is pending."""
    if not fired: return False
    groups={}
    for trg in fired: groups.setdefault(trg["controller_conn"],[]).append(trg)
    # APNAP ordering; this implementation's supported simultaneous events create one group.
    for controller_conn in ([active_conn,get_other_conn(active_conn)] if active_conn else list(groups)):
        group=groups.get(controller_conn,[])
        if len(group)>1:
            seq=next_server_seq(); pending_trigger_orders[controller_conn]={"seq":seq,"triggers":group}
            send_pdu(controller_conn,{"type":"TRIGGER_ORDER","seq_num":seq,"player_id":players[controller_conn]["player_id"],
                                      "trigger_ids":[x["trigger_id"] for x in group]})
        elif group: push_trigger(group[0])
    return True

def request_trigger_target(trigger, legal_targets):
    if not legal_targets: return False
    conn=trigger["controller_conn"]; seq=next_server_seq()
    pending_trigger_choices[conn]={"seq":seq,"trigger":trigger,"legal_targets":legal_targets}
    send_pdu(conn,{"type":"TRIGGER_CHOICE","seq_num":seq,"trigger_id":trigger["trigger_id"],
                   "source_id":trigger["source_id"],"effect_summary":trigger["effect"],
                   "requires_target":True,"legal_targets":legal_targets})
    return True

def handle_trigger_order_response(conn,pdu):
    pending=pending_trigger_orders.get(conn)
    if not pending or pdu.get("seq_num")!=pending["seq"]:
        error(conn,pdu,"TRIGGER_ORDER_INVALID","No matching trigger-order request."); return
    ids=pdu.get("ordered_trigger_ids",[]); by_id={x["trigger_id"]:x for x in pending["triggers"]}
    if not string_list(ids,True): error(conn,pdu,"TRIGGER_ORDER_INVALID","ordered_trigger_ids must be a unique string list."); return
    if len(ids)!=len(by_id) or set(ids)!=set(by_id): error(conn,pdu,"TRIGGER_ORDER_INVALID","Order must contain each trigger exactly once."); return
    del pending_trigger_orders[conn]
    for tid in ids: push_trigger(by_id[tid])
    if not pending_trigger_orders and not pending_trigger_choices: grant_priority(trigger_resume_conn or active_conn)

def handle_trigger_choice_response(conn,pdu):
    pending=pending_trigger_choices.get(conn)
    if not pending or pdu.get("seq_num")!=pending["seq"] or pdu.get("trigger_id")!=pending["trigger"]["trigger_id"]:
        error(conn,pdu,"TRIGGER_CHOICE_INVALID","No matching trigger-choice request."); return
    if not isinstance(pdu.get("accept"),bool): error(conn,pdu,"TRIGGER_CHOICE_INVALID","accept must be boolean."); return
    chosen=pdu.get("chosen_target")
    if not pdu.get("accept") or chosen not in pending["legal_targets"]:
        error(conn,pdu,"TRIGGER_CHOICE_INVALID","A required legal target must be accepted."); return
    trigger=pending["trigger"]; trigger["targets"]=[chosen]; del pending_trigger_choices[conn]; push_trigger(trigger)
    if not pending_trigger_orders and not pending_trigger_choices: grant_priority(trigger_resume_conn or active_conn)

def find_permanent(target):
    for owner_conn, p in players.items():
        for perm in p["battlefield"]:
            if perm.get("id") == target:
                return owner_conn, perm
    return None, None

def deal_damage(target, amount):
    for p in players.values():
        if p["player_id"] == target:
            p["life"] -= amount; return
    _, perm = find_permanent(target)
    if perm is not None: perm["damage"] = perm.get("damage", 0) + amount

def destroy_dead_creatures():
    died = []
    for p in players.values():
        for perm in list(p["battlefield"]):
            info = cards.get(perm["id"], {})
            if info.get("card_type") == "Creature" and perm.get("damage", 0) >= int(info.get("toughness") or 0) + perm.get("toughness_bonus", 0):
                p["battlefield"].remove(perm); p["graveyard"].append(perm["id"])
                died.append(perm["id"])
    return died

def resolve_stack_top():
    global consecutive_passes, trigger_resume_conn
    item = stack.pop(); card = cards[item["source_id"]]; controller = next(p for p in players.values() if p["player_id"] == item["controller_id"])
    name = card.get("card_name")
    result = "RESOLVED"; changes = []
    target = item["targets"][0] if item["targets"] else None
    if item["item_type"] == "TRIGGER_ABILITY":
        effect=item.get("trigger_effect")
        if effect=="PROWESS":
            _,perm=find_permanent(item["source_id"])
            if perm: perm["power_bonus"]=perm.get("power_bonus",0)+1; perm["toughness_bonus"]=perm.get("toughness_bonus",0)+1
            else: result="FIZZLE"
        elif effect=="SACRIFICE_SELF":
            owner,perm=find_permanent(item["source_id"])
            if perm: players[owner]["battlefield"].remove(perm); players[owner]["graveyard"].append(item["source_id"]); changes.append({"change_type":"SACRIFICE","target":item["source_id"]})
        elif effect=="GRAY_MERCHANT":
            devotion=sum(int(cards.get(p["id"],{}).get("cost",{}).get("B") or 0) for p in controller["battlefield"])
            opponent=players[get_other_conn(next(c for c,x in players.items() if x is controller))]; opponent["life"]-=devotion; controller["life"]+=devotion
            changes += [{"change_type":"DAMAGE","target":opponent["player_id"],"amount":devotion},{"change_type":"LIFE_GAIN","target":controller["player_id"],"amount":devotion}]
        elif effect=="GRAVEDIGGER":
            target=item["targets"][0] if item["targets"] else None
            if target in controller["graveyard"]: controller["graveyard"].remove(target); controller["hand"].append(target); changes.append({"change_type":"RETURN_TO_HAND","target":target})
            else: result="FIZZLE"
        elif effect=="GOBLIN_GUIDE":
            opponent=players[get_other_conn(next(c for c,x in players.items() if x is controller))]
            if opponent["library"] and cards.get(opponent["library"][-1],{}).get("card_type")=="Land": opponent["hand"].append(opponent["library"].pop())
    elif item["item_type"] == "ABILITY":
        if name in ("Prodigal Sorcerer", "Rod of Ruin") and target:
            deal_damage(target, 1); changes.append({"change_type":"DAMAGE","target":target,"amount":1})
        elif name == "Royal Assassin" and target:
            owner, perm = find_permanent(target)
            if perm and perm.get("tapped") and cards.get(target,{}).get("card_type") == "Creature":
                players[owner]["battlefield"].remove(perm); players[owner]["graveyard"].append(target); changes.append({"change_type":"DESTROY","target":target})
            else: result = "FIZZLE"
        elif name == "Millstone" and target:
            victim = next((p for p in players.values() if p["player_id"] == target), None)
            if victim:
                milled=[]
                for _ in range(min(2,len(victim["library"]))): milled.append(victim["library"].pop())
                victim["graveyard"].extend(milled); changes.append({"change_type":"MILL","target":target,"cards":milled})
            else: result="FIZZLE"
        elif name == "Merfolk Looter":
            if controller["library"]: controller["hand"].append(controller["library"].pop())
            # Discard choice is simplified to the last card; client-side choice would require another RFC PDU.
            if controller["hand"]: controller["graveyard"].append(controller["hand"].pop())
    elif name == "Counterspell" and target:
        victim = next((x for x in reversed(stack) if x["stack_item_id"] == target), None)
        if victim:
            stack.remove(victim); next(p for p in players.values() if p["player_id"] == victim["controller_id"])["graveyard"].append(victim["source_id"])
            changes.append({"change_type":"COUNTER", "target":target})
    elif name in ("Lightning Bolt", "Lava Spike") and target: deal_damage(target, 3); changes.append({"change_type":"DAMAGE","target":target,"amount":3})
    elif name == "Shock" and target: deal_damage(target, 2); changes.append({"change_type":"DAMAGE","target":target,"amount":2})
    elif name == "Searing Spear" and target: deal_damage(target, 3); changes.append({"change_type":"DAMAGE","target":target,"amount":3})
    elif name == "Flame Slash" and target: deal_damage(target, 4); changes.append({"change_type":"DAMAGE","target":target,"amount":4})
    elif name == "Giant Growth" and target:
        _, perm = find_permanent(target)
        if perm: perm["power_bonus"] = perm.get("power_bonus", 0) + 3; perm["toughness_bonus"] = perm.get("toughness_bonus", 0) + 3
        else: result = "FIZZLE"
    elif card.get("card_type") == "Creature":
        controller["battlefield"].append({"id": item["source_id"], "tapped": False, "damage": 0, "summoning_turn": turn_number})
    controller["graveyard"].append(item["source_id"]) if card.get("card_type") in ("Instant", "Sorcery") else None
    for dead in destroy_dead_creatures(): changes.append({"change_type":"DESTROY","target":dead})
    broadcast({"type": "STACK_RESOLVE", "seq_num": next_server_seq(), "stack_item_id": item["stack_item_id"], "result": result, "state_changes": changes})
    consecutive_passes = 0; broadcast_ingame_state()
    if game_phase == "IN_GAME":
        fired=[]
        if item["item_type"]=="SPELL" and card.get("card_type")=="Creature":
            new_conn=next(c for c,x in players.items() if x is controller)
            if name=="Gray Merchant of Asphodel": fired.append(make_trigger(new_conn,item["source_id"],"GRAY_MERCHANT"))
            elif name=="Gravedigger":
                legal=[cid for cid in controller["graveyard"] if cards.get(cid,{}).get("card_type")=="Creature"]
                trg=make_trigger(new_conn,item["source_id"],"GRAVEDIGGER")
                if request_trigger_target(trg,legal): return
        trigger_resume_conn = active_conn
        queue_triggers(fired)
        if not pending_trigger_orders and not pending_trigger_choices: grant_priority(active_conn)

def handle_discard(conn, pdu):
    with lock:
        player = players.get(conn); ids = pdu.get("card_ids")
        if not string_list(ids,True): error(conn,pdu,"ILLEGAL_ACTION","card_ids must be a unique string list."); return
        if game_phase != "IN_GAME" or current_step != "CLEANUP" or conn != active_conn:
            error(conn, pdu, "WRONG_PHASE", "DISCARD is only accepted from the active player in CLEANUP."); return
        expected = player.get("last_state_seq_num")
        if pdu.get("seq_num") != expected: error(conn, pdu, "STALE_ACTION", f"Expected seq_num {expected}."); return
        if not isinstance(ids, list) or len(ids) != len(player["hand"]) - 7 or any(i not in player["hand"] for i in ids) or len(ids) != len(set(ids)):
            error(conn, pdu, "ILLEGAL_ACTION", "Discard exactly the excess cards from your hand."); return
        for i in ids: player["hand"].remove(i); player["graveyard"].append(i)
        finish_cleanup_step()

def creature_stats(perm):
    info = cards.get(perm["id"], {})
    return int(info.get("power") or 0) + perm.get("power_bonus", 0), int(info.get("toughness") or 0) + perm.get("toughness_bonus", 0)

def handle_declare_attackers(conn, pdu):
    global attackers, trigger_resume_conn
    with lock:
        if current_step != "DECLARE_ATTACKERS" or conn != active_conn:
            if current_step == "DECLARE_ATTACKERS" and conn != active_conn: error(conn, pdu, "ILLEGAL_ACTION", "Only active player declares attackers.")
            return
        if pdu.get("seq_num") != combat_request_seq:
            error(conn, pdu, "STALE_ACTION", f"Expected phase token {combat_request_seq}."); return
        declarations = pdu.get("attackers", [])
        if not isinstance(declarations, list) or any(not isinstance(x,dict) or not string_id(x.get("creature_id")) or not string_id(x.get("target")) for x in declarations):
            error(conn, pdu, "ILLEGAL_ACTION", "attackers must be a list."); return
        ids = [x.get("creature_id") if isinstance(x, dict) else x for x in declarations]
        opponent_id = players[get_other_conn(conn)]["player_id"]
        if len(ids) != len(set(ids)) or any(isinstance(x, dict) and x.get("target") != opponent_id for x in declarations):
            error(conn, pdu, "ILLEGAL_ACTION", "attackers must be a unique list."); return
        by_id = {x["id"]: x for x in players[conn]["battlefield"]}
        for cid in ids:
            perm = by_id.get(cid); info = cards.get(cid, {})
            haste = "haste" in str(info.get("effect", "")).lower()
            if not perm or info.get("card_type") != "Creature" or perm.get("tapped") or (perm.get("summoning_turn") == turn_number and not haste):
                error(conn, pdu, "ILLEGAL_ACTION", f"{cid} cannot attack."); return
        attackers = ids
        for cid in ids: by_id[cid]["tapped"] = True
        if not attackers:
            transition_to("END_OF_COMBAT")
        else:
            # Attackers are locked in; AP receives priority before blockers.
            broadcast_ingame_state()
            fired=[make_trigger(conn,cid,"GOBLIN_GUIDE") for cid in attackers if cards.get(cid,{}).get("card_name")=="Goblin Guide"]
            trigger_resume_conn=active_conn; queue_triggers(fired)
            if not pending_trigger_orders and not pending_trigger_choices: open_priority_window()

def handle_declare_blockers(conn, pdu):
    global blockers
    with lock:
        if current_step != "DECLARE_BLOCKERS" or conn == active_conn: return
        if pdu.get("seq_num") != combat_request_seq:
            error(conn, pdu, "STALE_ACTION", f"Expected phase token {combat_request_seq}."); return
        raw = pdu.get("blockers", {})
        if not isinstance(raw,list) or any(not isinstance(x,dict) or not string_id(x.get("creature_id")) or not string_id(x.get("blocking_id")) for x in raw):
            error(conn,pdu,"ILLEGAL_ACTION","blockers must contain creature_id/blocking_id string objects."); return
        # RFC: [{creature_id: blocker, blocking_id: attacker}].
        pairs = raw if isinstance(raw, list) else [{"creature_id": b, "blocking_id": a} for b, a in raw.items()] if isinstance(raw, dict) else []
        own = {x["id"]: x for x in players[conn]["battlefield"]}
        seen = set(); parsed = {}
        for pair in pairs:
            b, a = pair.get("creature_id", pair.get("blocker_id")), pair.get("blocking_id", pair.get("attacker_id"))
            if b in seen or b not in own or cards.get(b, {}).get("card_type") != "Creature" or own[b].get("tapped") or a not in attackers:
                error(conn, pdu, "ILLEGAL_ACTION", "Illegal blocker assignment."); return
            seen.add(b); parsed.setdefault(a, []).append(b)
        blockers = parsed
        # Blockers are locked in; AP receives priority before damage ordering.
        broadcast_ingame_state()
        open_priority_window()

def handle_damage_order(conn, pdu):
    global damage_orders
    with lock:
        if current_step != "ASSIGN_DAMAGE_ORDER" or conn != active_conn: return
        if pdu.get("seq_num") != combat_request_seq:
            error(conn, pdu, "STALE_ACTION", f"Expected phase token {combat_request_seq}."); return
        attacker = pdu.get("attacker_id")
        order = pdu.get("blocker_order")
        if not string_id(attacker) or not string_list(order,True): error(conn,pdu,"ILLEGAL_ACTION","Invalid attacker_id or blocker_order."); return
        if attacker not in blockers or not isinstance(order, list) or set(order) != set(blockers[attacker]):
            error(conn, pdu, "ILLEGAL_ACTION", "blocker_order must list every blocker for attacker_id exactly once."); return
        damage_orders[attacker] = order
        required = {a for a, bs in blockers.items() if len(bs) > 1}
        if required.issubset(damage_orders): begin_combat_damage()
        else: grant_priority(active_conn)

def has_first_strike(card_id):
    return "first strike" in str(cards.get(card_id, {}).get("effect", "")).lower()

def begin_combat_damage():
    combatants = attackers + [b for values in blockers.values() for b in values]
    if any(has_first_strike(x) for x in combatants):
        transition_to("FIRST_STRIKE_DAMAGE")
        resolve_combat_damage(first_strike=True)
    else:
        transition_to("COMBAT_DAMAGE")

def transition_to(step):
    global current_step, combat_request_seq
    old = current_step; current_step = step
    seq = next_server_seq()
    if step in ("DECLARE_ATTACKERS", "DECLARE_BLOCKERS", "ASSIGN_DAMAGE_ORDER"):
        combat_request_seq = seq
    broadcast({"type": "PHASE_TRANSITION", "seq_num": seq, "from_phase": old,
               "to_phase": step, "active_player": players[active_conn]["player_id"], "turn": turn_number})
    enter_step(step)

def resolve_combat_damage(first_strike=False):
    defender = get_other_conn(active_conn); assignments = []
    for aid in attackers:
        _, aper = find_permanent(aid)
        if not aper: continue
        attacker_strikes = has_first_strike(aid) == first_strike
        apower, _ = creature_stats(aper); bs = blockers.get(aid, [])
        if not bs:
            if attacker_strikes:
                players[defender]["life"] -= apower; assignments.append({"source": aid, "target": players[defender]["player_id"], "amount": apower})
            continue
        remaining = apower
        for bid in damage_orders.get(aid, bs) if attacker_strikes else []:
            _, bper = find_permanent(bid)
            if not bper: continue
            _, btough = creature_stats(bper); lethal = max(0, btough - bper.get("damage", 0)); amount = min(remaining, lethal)
            bper["damage"] = bper.get("damage", 0) + amount; remaining -= amount
            assignments.append({"source": aid, "target": bid, "amount": amount})
        striking_blockers = [b for b in bs if has_first_strike(b) == first_strike]
        retaliation = sum(creature_stats(find_permanent(b)[1])[0] for b in striking_blockers if find_permanent(b)[1])
        aper["damage"] = aper.get("damage", 0) + retaliation
        assignments.extend({"source": b, "target": aid, "amount": creature_stats(find_permanent(b)[1])[0]} for b in striking_blockers if find_permanent(b)[1])
    died = destroy_dead_creatures()
    broadcast({"type": "COMBAT_DAMAGE_RESULT", "seq_num": next_server_seq(), "damage_events": assignments,
               "life_totals": {p["player_id"]: p["life"] for p in players.values()}, "creatures_died": died})
    broadcast_ingame_state()
    if game_phase != "IN_GAME": return
    if first_strike:
        # State-based actions occur, then players receive priority before normal damage.
        open_priority_window()
    else:
        transition_to("END_OF_COMBAT")

def handle_client(conn, addr):
    print(f"[S] Handling client {addr}")
    try:
        while True:
            try:
                pdu = recv_pdu(conn)
            except (ValueError, UnicodeDecodeError, json.JSONDecodeError) as exc:
                send_pdu(conn, {"type": "ERROR", "seq_num": 0, "code": "INVALID_JSON", "message": str(exc)})
                if str(exc) == "INVALID_LENGTH": break  # stream boundary cannot be recovered safely
                continue
            if pdu is None:
                print(f"[S] Client {addr} disconnected")
                # If disconnected during an active game, remaining player wins
                handle_disconnect(conn)
                break

            msg_type = pdu.get("type")

            if msg_type == "PING":
                send_pdu(conn, {"type": "PONG", "seq_num": pdu.get("seq_num", 0), "timestamp": pdu.get("timestamp", 0)})
            elif msg_type == "PLAYER_READY":
                handle_player_ready(conn, pdu)
            elif msg_type == "MULLIGAN_CHOICE":
                handle_mulligan_choice(conn, pdu)
            elif msg_type == "PRIORITY_PASS":
                handle_priority_pass(conn, pdu)
            elif msg_type == "PLAY_LAND":
                handle_play_land(conn, pdu)
            elif msg_type == "CAST_SPELL":
                handle_cast_spell(conn, pdu)
            elif msg_type == "ACTIVATE_ABILITY":
                handle_activate_ability(conn, pdu)
            elif msg_type == "DISCARD":
                handle_discard(conn, pdu)
            elif msg_type == "DECLARE_ATTACKERS":
                handle_declare_attackers(conn, pdu)
            elif msg_type == "DECLARE_BLOCKERS":
                handle_declare_blockers(conn, pdu)
            elif msg_type == "ASSIGN_DAMAGE_ORDER":
                handle_damage_order(conn, pdu)
            elif msg_type == "TRIGGER_ORDER_RESPONSE":
                handle_trigger_order_response(conn, pdu)
            elif msg_type == "TRIGGER_CHOICE_RESPONSE":
                handle_trigger_choice_response(conn, pdu)
            elif msg_type == "CONCEDE":
                handle_concede(conn, pdu)
            else:
                send_pdu(conn, {
                    "type": "ERROR",
                    "seq_num": pdu.get("seq_num", 0),
                    "code": "UNKNOWN_TYPE",
                    "message": f"Unhandled type: {msg_type}"
                })
    except OSError:
        handle_disconnect(conn)
    finally:
        conn.close()
        with lock:
            if conn in connected_clients:
                connected_clients.remove(conn)
            # Only delete from players dict if in LOBBY/GAME_OVER (not waiting on a reconnect timer)
            if conn in players and game_phase not in ("IN_GAME", "MULLIGAN"):
                del players[conn]

while True:
    conn, addr = server_socket.accept()

    with lock:
        if len(connected_clients) >= 2:
            print(f"[S] Refusing extra connection from {addr}")
            conn.close()
            continue
        connected_clients.append(conn)

    print(f"[S] Accepted connection from {addr} ({len(connected_clients)}/2)")
    thread = threading.Thread(target=handle_client, args=(conn, addr))
    thread.daemon = True
    thread.start()
